### ISSUE TITLE
Affichage des détails d'un produit 

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#1]
Sur la page "Mon Panier" (https://beta.stolons.org/WeekBasket), il faut clicker sur le produit pour voir le détail.
Ce serait bien d'avoir directement le détail lors du survol ou d'une autre manière car le fait de clicker n'est pas intuitif et utilisé.

**Comment by dyslesiq** [comment]
Je pense qu'on peut reporter cette implem. Personnellement je ne suis pas fan des modale énormes qui apparaissent automatiquement.
D'autant que cliquer sur l'image du produit pour avoir le détail parait assez intuitif.

**Comment by ChavFDG** [comment]
En effet, en plus sur portable ça ne passerait pas. Il faudrait peut être ajouter un petit "?" / symbole d'information quelque part. A réfléchir en fonction des retours utilisateurs.

A savoir que cette implémentation n'est pas dans la version 2.0 ( à faire pour le 29 )
