### ISSUE TITLE
BUG, des produits apparaissent comme indisponibles pour un consommateur alors qu'ils ont été rendus disponibles par le producteur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#10]
En tant que producteur, je me place en mode livraison et je rends mes produits disponibles puis je repasse en mode commande.
Je me connecte via un autre compte d'un adhérent consommateur et je constate que les produits auparavant rendus disponibles apparaissent bien dans mes choix de produits mais en tant que "produits indisponibles".

**Comment by dyslesiq** [comment]
C'est corrigé! Il s'agissait en fait d'un bug côté producteur pour l'édition des produits. L'ajout du stock d'un produit était inversé, cad qu'ajouter 2Kg en enlevait 2...
Et le produit était ensuite considéré comme indisponible car ayant un stock < à 0.
