### ISSUE TITLE
photo sur page d'accueil du stolon

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#100]
en attendant de mettre carte des producteurs, pouvez vous mettre cette photo car il y a un gros blanc !!
![desaignes](https://user-images.githubusercontent.com/32641097/36196621-a0be1d26-1171-11e8-9b0b-92c0c3da48fd.JPG)

**Comment by ChavFDG** [comment]
De manière temporaire j'ai supprimer ( mis en commentaire ) la carte des stolons qui merdé.
