### ISSUE TITLE
mail envoi identifiant et mot de passe

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#101]
bonjour

depuis quelques temps les consommateurs ne reçoivent plus de mail lors de la création de leur compte qui leur indique leur identifiant et mot de passe !

**Comment by ChavFDG** [comment]
Nico à corriger le problème hier dans le #82 .
Peux tu vérifier si c'est bien le cas s'il te plait ?

**Comment by JeanneVoiry** [comment]
re problème : 
j'ai retesté ce matin avec le mail perso de ma collègue (Céline VENOT dans Stolon de Privas) et elle n'a pas reçu le mail d'ouverture de compte..

**Comment by ChavFDG** [comment]
J'ai refait un essaie ça passe sur mon PC en local. A re tester après la migration.

**Comment by JeanneVoiry** [comment]
je viens de retester en local sur beta.stolons.org sur le Stolon de Privas avec deux adresses yopmail (stolons@yopmail.com et conso@yopmail.com), on ne reçoit aucun mail

**Comment by JeanneVoiry** [comment]
hello, 
d'ici mon départ le 31 mai, il faudrait que le mail de création de compte s'envoie tout seul (car jusqu'à présent c'était moi qui le faisait et les producteurs ne le feront pas à ma place!!)

de plus, dans ce mail de création de compte, il faut mettre les informations indispensables du Stolon d'Aubenas : 

Je vois un texte comme cela par exemple : 

"Bonjour,

Vous bénéficiez désormais d'un compte consommateur sur le site https://aubenas.stolons.org
Pour vous connecter, votre identifiant et votre mot de passe sont identiques par défaut, il s'agit de votre adresse mail.

**Qu'est-ce que le Stolon d'Aubenas ?**
Une association qui réunit des producteurs 100% bio ou en dernière année de conversion, dont les fermes sont situées à moins de 50 km d'Aubenas et qui vendent leurs produits en ligne au prix de vente directe pratiqué sur le territoire.
Ces critères sont garantis par Agri Bio Ardèche, l'association des producteurs bio du département qui a accompagné la création du Stolon d'Aubenas.

**Quand commander ?**
De samedi matin (00h01) à lundi soir (23h59) vous pourrez vous connecter sur https://aubenas.stolons.org/ et vous rendre sur "mon panier" pour commander les produits. Vous n'avez aucune obligation de commander chaque semaine.

**Où récupérer son panier ?**
Chaque mercredi, rendez-vous à la Halle Chaussabel au 32 chemin de Roqua entre 17h30 et 19h pour venir récupérer votre panier auprès des producteurs qui assurent la permanence. La Halle est située derrière le gymnase Roqua. Vous pourrez vous garer devant le gymnase ou devant la halle Chaussabel. Nous vous conseillons d'apporter sacs et cabas pour emporter vos produits. Le paiement se fera sur place, par chèque et espèces uniquement.

**Pour toute question :** 
_adressemail de l'association_
