### ISSUE TITLE
impossible de désactiver un compte

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#103]
La consommatrice Jacqueline GALLIC m'a informé qu'elle ne souhaitait plus avoir de compte sur Stolon

que dois-je faire pour être sûre qu'elle ne reçoivent plus d'emails ?
supprimer le compte simplement ou aussi le désactiver auparavant ?

d'ailleurs, quand j'essaie de désactiver le compte => message "une erreur est survenue" apparaît

par ailleurs, on pourrait ajouter une option "se désabonner de la liste d'envoi des mails"

**Comment by ChavFDG** [comment]
C'est noté. Il suffit de le supprimer théoriquement.

**Comment by ChavFDG** [comment]
J'ai fait un essaie de désactivation ainsi que de suppression du compte de Gallic en local et cela fonctionne.
Est il possible de confirmer que ça ne marcher pas?

**Comment by JeanneVoiry** [comment]
j'ai déjà supprimé le compte de Gallic (sans l'avoir désactivé auparavant car ça ne marchait pas)

**Comment by JeanneVoiry** [comment]
d'ailleurs ça pose des soucis car j'ai fait la même chose avec un de mes comptes (supprimer sans désactiver) => je n'apparais plus dans la liste des adhérents par contre je peux toujours me connecter !!

**Comment by JeanneVoiry** [comment]
j'ai essayé de désactiver un autre compte (Céline Venot sur Stolon de Privas) => message d'erreur apparaît

**Comment by ChavFDG** [comment]
Pourrais-tu me faire une copie d'écran du message d'erreur s'il te plait ?

**Comment by JeanneVoiry** [comment]
![image](https://user-images.githubusercontent.com/32641097/37275828-84cfbc2c-25e0-11e8-8c20-b330132d9cbf.png)

**Comment by ChavFDG** [comment]
Je n'ai pas réussie a reproduire le cas mais pas mal d'amélioration faite à tester.

**Comment by JeanneVoiry** [comment]
la désactivation du compte marche bien (testé en local sur beta.stolons.org avec l'utilisateur stolons@yopmail.com
Puis j'ai supprimé ce compte.

Par contre, j'ai essayé de supprimer directement sans désactiver un autre compte (conso@yopmail.com) et le message suivant est apparu : 
![image](https://user-images.githubusercontent.com/32641097/37343415-cb473396-26c7-11e8-8703-9e717ca2b31b.png)

J'ai fait retour en arrière et je suis tombée sur la page des consommateurs, il n'était plus dans la liste;

J'ai essayé de me connecter sur son compte pour voir s'il avait bien été supprimé et le même message apparaît.

**Comment by JeanneVoiry** [comment]
aujourd'hui j'ai réessayé de supprimer un compte sur le stolon d'aubenas en local sur https://beta.stolons.org/Users  : il s'agit du GAEC DU PIED PALET, compte n°6 qui est en doublon (le bon compte est le n° 17, GAEC DU PIED PALET)
=> la désactivation du compte fonctionne
=> quand je fais ensuite "supprimer le compte", le message d'erreur apparaît 

![image](https://user-images.githubusercontent.com/32641097/37392188-bf6c8598-276d-11e8-8f7a-d2793ca4c20c.png)

et le compte est toujours en visible dans la liste des producteurs

Cela pose problème car on a ce doublon du GAEC DU PIED PALET dans l'onglet "nos producteurs"

**Comment by ChavFDG** [comment]
Après test cela fonctionne à nouveau
