### ISSUE TITLE
doublon mail d'ouverture des commandes

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#104]
Suite à la correction de l'envoi automatique du mail d'ouverture des commandes, j'ai reçu deux mails ce weekend pour le Stolon d'Aubenas : 
- un mail le samedi matin et un mail le dimanche matin

**Comment by ChavFDG** [comment]
Cela venait du fait qu'on avait copier la base de donnée de prod afin de faire les tests. Par conséquent quand on fait un test chez nous ça envoie un mail à tout le monde.
