### ISSUE TITLE
impossible de télécharger factures et bon de commande en pdf

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#111]
sur beta.stolons, 
dans Stolon d'Aubenas, quand j'essaie de télécharger une facture producteur, une facture consommateur ou un bon de commande producteur, un message d'erreur apparaît : 

![image](https://user-images.githubusercontent.com/32641097/37344227-1cd3bde0-26ca-11e8-906a-fd4a2267bbc8.png)

**Comment by ChavFDG** [comment]
Il faut essayer sur une factures que tu viens de générer. Pas sur des
anciennes factures qui ne sont pas présente sur le site.

2018-03-13 14:24 GMT+01:00 JeanneVoiry <notifications@github.com>:

**Comment by dyslesiq** [comment]
C'est ok depuis quelques temps
