### ISSUE TITLE
Marge différente selon type de producteurs

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#112]
Il y aura deux types de producteurs au sein d'un Stolon : 
- producteurs en dépôt-vente : ce sont les producteurs qui ne font aucune permanence
- les producteurs actifs qui font la permanence.

les producteurs du Stolon d'Aubenas souhaitent une commission différente entre ces deux types de producteurs pour inciter les producteurs à faire des permanences. Il faudrait donc un système de deux marges différentes.

Je le vois ainsi : 

depuis un compte administrateur, quand on fait créer un producteur 

![image](https://user-images.githubusercontent.com/32641097/37390651-19872bf0-2769-11e8-9cab-e570841ae1ac.png)

entre "Subscription aux mail" et "Informations producteurs", ajouter "Statut du producteur" : deux cases à cocher : producteur / producteur en dépôt-vente

puis dans Administration, quand on modifie les conditions du Stolon, 

![image](https://user-images.githubusercontent.com/32641097/37390830-9dc24d50-2769-11e8-8c91-a66b696d054f.png)
 
ajouter l'option "montant de la commission sur les producteurs en dépôt-vente (en %)" dans l'onglet "commissions"

il faudra alors relier le tout à l'édition des factures en séparant bien les deux types de producteurs.

**Comment by ChavFDG** [comment]
Après discutions avec Benoit. Voici une proposition en attente de validation :

- dans la configuration du stolon 
     - Avoir une commission pour les producteurs ( reste )
     - Montant de la commission => Montant de la commission par défaut
- ajouter pour chaque producteur / par stolon la possibilité de configurer ça commission

De cette manière si un stolon à plusieurs commission en fonctions de plusieurs cas, voir même cas particulier le système est plus souple que des catégories fixes de type de commissions.

Exemple :
- Producteur en dépot vente
- Producteur en dépot vente effectuant des permanences
- Producteur venant livrer mais sans faire de permanence
- Producteur venant livrer en faisant des permanences ......

A valider ?

**Comment by Benoitab07** [comment]
yo,
il faudrait que ces modifications puissent se faire que depuis le compte administrateur et non depuis chaque compte producteur. par exemple un producteur en dépot vente ne sera pas administrateur, il ne fat pas qu'il puisse lui même modifier sa commission ;
sinon ok ça permet de faire face a toutes les éventualités

**Comment by ChavFDG** [comment]
C'est bon, c'est déjà le cas. Seul les administrateurs du stolon peuvent modifier cette valeur.
