### ISSUE TITLE
mail automatique : venez chercher votre panier!

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#117]
la boulangère du Stolon d'Aubenas a eu une super idée 
comme à chaque fois des consommateurs oublient de venir récupérer leur panier (2 cette semaine!), on pourrait leur envoyer un mail automatique type : 

Votre panier du Stolon d'Aubenas est disponible ce soir, de 17h30 à 19h, à la Halle Chaussabel au 32 chemin de Roqua (derrière le gymnase).

ce mail serait envoyer le jour de livraison, uniquement aux consommateurs qui ont commandé par contre !!

**Comment by ChavFDG** [comment]
- possibilité de choisir s’ils veulent recevoir ou non avec par défaut ils le reçoivent
- oui ajouter « mail de rappel de commande »
- 12h peut etre une heure d’envoi pas mal
