### ISSUE TITLE
quantité de stock proposé différent de la quantité stock de la semaine => peu intuitif pour le producteur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#12]
en tant que producteur, quand je rends disponible un produit, la quantité inscrite dans "stock de la semaine" est égale à la quantité entrée dans "stock proposé" (voir encadré blanc et verre sur photos ci-dessous) multipliée par le palier choisi.
dans l'exemple ci-dessous, le montant total des carottes est de 15 kg = 30 kg (stock proposé) * 0,5 kg (palier choisi).

Je trouve que cette méthode de calcul peut prêter à confusion, car on aurait envie de croire que le "stock proposé" est égale au "stock de la semaine", c'est-à-dire au stock total qu nous mettons en vente en tant que producteur...

![image](https://user-images.githubusercontent.com/32641097/32551303-5d1a4366-c490-11e7-996f-e1672a5c859c.png)

**Comment by dyslesiq** [comment]
Il n'y a plus ce comportement depuis quelques temps déjà
