### ISSUE TITLE
mail ouverture des commandes

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#120]
la consommatrice Dominique Perge du Stolon d'Aubenas (n°29) m'a indiqué que pendant un temps elle ne recevait plus les mails d'ouvertures des commandes (même dans ces spams) et la semaine dernière elle l'a reçu le dimanche.

**Comment by ChavFDG** [comment]
Problème global au niveau des mails. Certains passe en spam, d'autres avait été envoyé par nous lors de test. Et pour finir on c'est fait bloquer chez plusieurs personnes. On est dessus.
