### ISSUE TITLE
ajouter récapitulatif ventes totales de la semaine

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#122]
Pour que le groupe de producteurs ait une meilleure visibilité des ventes totales hebdomadaires du Stolon, je propose que dans l'onglet "gérer les paniers" il y ait un bouton "ventes de la semaine" en dessous de "télécharger les factures consommateurs" avec dedans : le montant des ventes par producteurs avec deux colonnes (Colonne qui indique le montant de la vente TTC en euros et colonne qui indique la commission prélevée sur les ventes de chaque producteurs) avec un TOTAL de ces deux colonnes.

pour le moment, les producteurs n'ont pas de visibilité et c'est moi qui leur sort les chiffres, que je récupère à la main en reprenant les données de chaque facture, chaque semaine.

**Comment by ChavFDG** [comment]
Au niveau de la visibilité les producteurs peuvent aller voir leurs factures directement sur le site ici :
![image](https://user-images.githubusercontent.com/16624098/41720396-384d3122-7563-11e8-872f-06084fe6845b.png)
