### ISSUE TITLE
faire apparaître site stolon dans moteur de recherche

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#125]
1. faire apparaître site stolon dans moteur de recherche

à la permanence de Stolon d'Aubenas hier soir des consommateurs m'ont fait remarqué que quand on tape "stolon aubenas" sur google on ne tombe pas sur le lien https://www.google.fr/search?source=hp&ei=vIvYWvztDMP4wALX-J6YBw&q=stolon+aubenas&oq=stolon+aubenas&gs_l=psy-ab.3...2996.4686.0.4988.16.15.0.0.0.0.246.1378.9j4j1.15.0....0...1c.1.64.psy-ab..1.13.1120.0..0j0i131k1j0i10k1j0i22i30k1j33i160k1.54.muPtkeLXTdw

**Comment by JeanneVoiry** [comment]
d'après IKOULA, pour un meilleur référencement du site il faudrait : 
"Attention vous n'avez pas fait de redirection de stolons.org vers www.stolons.org > donc attention google vous pénalise dans le référencement avec du duplicate content"

**Comment by dyslesiq** [comment]
J'ai mis en place la redirection de stolons.org vers www.stolons.org.
Je vais regarder rapidement si il y a des choses simple à mettre en place pour améliorer le référencement.

**Comment by dyslesiq** [comment]
Je ferme ce bug qui est en dupliqué avec le #198
