### ISSUE TITLE
Impossible de supprimer un produit

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#13]
En tant que producteur, alors que je suis en mode livraison et mise à jour des stocks, quand j'essaie de supprimer un de mes produits (clique droit, supprimer), un message d'erreur aplaraît : 

![image](https://user-images.githubusercontent.com/32641097/32551761-e056044e-c491-11e7-8312-9cd9435af8ca.png)

**Comment by ChavFDG** [comment]
Il faut ajouter la gestion de la suppression d'un produit (uniquement quand ce dernier n'a jamais été acheté)
Il faut aussi ajouter la gestion de l'archivage d'un produit. Un produit archivé passe en mode archivé. Il n'est plus disponible dans la liste des produits à gérer, ne peux plus être modifié mais il peut être repasser en produits.

**Comment by JeanneVoiry** [comment]
ça fonctionne
