### ISSUE TITLE
Bug Stolon les Vans

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#132]
Suite à la création du Stolon des Vans, 
des bugs bizarres sont apparus : 

1. depuis mon compte consommateur jeanne.voiry@gmail .com, c'est le panier du Stolon test qui s'affichait jeudi 17 mai après-midi (alors qu'après nouvel essai le soir même c'était le bon panier qui s'affichait)

2. dans la gestion des stock du producteur Joel Sauvant, quand on renseigne un stock en KG on trouve un chiffre à rallonge en grammes qui n'a rien à voir, cf capture d'écran : 
![image](https://user-images.githubusercontent.com/32641097/40407142-bb7d287a-5e63-11e8-89fc-357cf939dd3d.png)

j'ai essayé de supprimer un produit et de le réenregistrer et la mise à jour du stock fonctionnait normalement.

c'est bizarre car quand j'ai créé le stolon test je n'ai pas eu tous ces bugs!

**Comment by ChavFDG** [comment]
Nous avons constaté le bug mais n'arrivons pas à le reproduire. On a fait une mise à jour pour que quand un produit est créé le stock soit automatiquement mis à zéro.
A voir dans le temps si ça se reproduit.
