### ISSUE TITLE
ajout d'un consommateur existant - bug sur beta.stolons

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#134]
Même bug que l'autre fois
quand j'ajoute un consommateur existant d'un autre stolon dans le stolon des Vans sur beta.stolons, le message d'erreur suivant s'affiche 

![image](https://user-images.githubusercontent.com/32641097/40616042-b1fd9e9a-6289-11e8-8d90-04d1e69b169a.png)

**Comment by ChavFDG** [comment]
Doublon avec le #133. Corrigé mais pas encore en ligne.
