### ISSUE TITLE
Enlever description produit obligatoire

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#136]
enlever la description du produit obligatoire pour valider édition d'un produit : 
![image](https://user-images.githubusercontent.com/32641097/40767428-ca266b66-64b2-11e8-9213-a2df7508ae08.png)

**Comment by ChavFDG** [comment]
On pense qu'il faut que la description soit obligatoire quitte à ce que ce soit un copier coller du nom. Ca permet au producteur de chercher à détailler un minimum ces produits.
