### ISSUE TITLE
bug dans édition d'un produit : prix au kg

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#137]
il est désormais impossible d'éditer un produit car bug sur le prix au kg, voir capture d'écran ci dessous 

![image](https://user-images.githubusercontent.com/32641097/40767472-e8558e0a-64b2-11e8-93df-1614f7a5c8fb.png)

**Comment by dyslesiq** [comment]
C'est corrigé et mis en ligne.
