### ISSUE TITLE
bug - vente à la pièce

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#138]
quand on choisit mode de vente à la pièce, 
la rubrique "prix au kg" ne disparait pas 
![image](https://user-images.githubusercontent.com/32641097/40767774-c6c3a6fe-64b3-11e8-9fd2-17d4ec626e47.png)

Il me semble qu'elle était grisée avant sur l'ancienne version. Désormais, pour la faire disparaitre, il faut cocher la case "masquer le prix au KG".
Or, on ne peut pas éditer un produit dans la version actuelle du site, si on ne coche pas la case "masquer le prix au KG" car il y a un bug sur la rubrique " prix au KG". voir issue [137)

**Comment by dyslesiq** [comment]
C'est corrigé et mis sur le stolons d'aubenas et le site de beta.
