### ISSUE TITLE
Problème de changement de mail d'un utilisateur

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#139]
Sur le stolons d'Aubenas :

> Je me permet de vous contacter car j’ai un problème de connexion à mon compte stolon.
> En effet, j’ai souhaité changer l’adresse mail utilisée pour me connecter au stolon et depuis le site ne reconnaît pas cette nouvelle adresse mais ne me permet pas non plus de me connecter avec l’ancienne.
> Voici les informations :
> Ancienne adresse mail : maximilien.n@orange.fr
> Nouvelle adresse :
> fournier.marilyne@gmail.com

**Comment by ChavFDG** [comment]
Même problème avec le compte suivant : chenaux.ludivine@gmail.com

> J'ai refait plusieurs tentatives mais c'est toujours pareil, cela m'indique erreur dans la saisie du mot de passe. Si je redemande un MDP avec l'adresse gmail, il m'indique qu'il a envoyé un mail mais je ne l'ai pas, ni dans les spams ni ailleurs et aux tentatives suivantes pour modifier le MDP, il indique qu'une erreur est survenue...

De plus impossible de supprimer le compte.

**Comment by ChavFDG** [comment]
On ne peux pas supprimer l'adhérent d'un stolon si il a des factures dans ce stolons. 
Si on fait ça on perd l'historique que l'on a ajouté sur les factures.

Proposition à réfléchir : tager l'adhérent comme supprimer => partout dans le code faire des selections des adhérents non supprimé. Cela nous permet de garder tout l'historique des factures pour un adhérent.
Un adhérent  dans plusieurs stolons qui en arrête un ne perdra pas son historique.

**Comment by dyslesiq** [comment]
Le changement d'adresse mail pose toujours problème: on peut bien changer son adresse mais ensuite impossible de se reconnecter (On a déja une erreur 401 à la suite du formulaire).

Première supposition: la couche d'authentification dotnet utilise l'adresse mail et ne reconnait plus l'utilisateur suite à un changement de celle-ci

**Comment by ChavFDG** [comment]
Je viens de changer le système de changement d'adresse mail par ce qu'il faut faire. A savoir :
- Seul l'utilisateur peut changer son mail depuis son profil
- Il rentre la nouvelle valeur via un formulaire spécifique
- Un lien de confirmation lui est envoyé à la nouvelle adresse mail, il clique dessus
- On changer l'adresse mail dans le ApplicationUser et le Adherent

Ca fonctionne bien, mais je n'arrive plus à me reconnecter derrière, le mot de passe est alors incorrecte ...

**Comment by ChavFDG** [comment]
Ok c'est réglé.
En fait dans AspUser on a plusieurs champs, à savoir :

- Email
- NormalizeEmail
- UserName
- NormalizeUsername

Jusqu'à maintenant on ne changé que la valeur Email. Avec la version précédente on changé le Email et le NormalizeEmail.
La connexion ne fonctionnait pas car la fonction de connexion compare le UserName/NormalizeUserName et le mot de passe .... qui eux n'était pas changé au moment de la changement du mail.
Car étant donné qu'on fait une connexion par mail/mdp on avait mis le username à la même valeur que le mail.

Bref maintenant au moment de la validation du nouveau mail on change bien le mail et le user name et leurs version Normalize. Et ça marche 👍

**Comment by JeanneVoiry** [comment]
ok ça marche
