### ISSUE TITLE
logo produits frais ne s'affiche pas

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#14]
En tant que consommateur, quand je fais mes courses en ligne, dans l'onglet "mon panier", le logo des produits frais ne s'affiche pas (voir ci-dessous) 

![image](https://user-images.githubusercontent.com/32641097/32552244-994c8d96-c493-11e7-9ed2-116056a099ab.png)

**Comment by ChavFDG** [comment]
Il n'y a pas de logo pour produit frais. Il faut qu'on en ajoute un. Il faudrait faire la liste des logos manquant pour les familles de produits afin de passer une commande à notre illustratrice.
On peut ajouter : 
- Produit frais
- Viande

**Comment by JeanneVoiry** [comment]
Bonne idée !

**Comment by ChavFDG** [comment]
N'hésite pas à ajouter les autres idées que tu as de manière à ce que je fasse une liste complète et une mise à jours d'un coup !

**Comment by ChavFDG** [comment]
En attendant de produire de nouveau logo pour ces type de produit il faudrait mettre un logo par défaut. Ce peut être encore le fameux panier.

**Comment by ChavFDG** [comment]
Ajouter les catégories suivantes :
Boulangerie : pains, pâtisseries, farines
Fruits
légumes
Produits laitiers
Oeufs
Viandes : volaille, boeuf, agneau, conserves
Conserves végétales : confitures, tartinades, autres
Boissons : alcool, sans alcool
Distributeur : légumineuses, fruits secs, céréales, boissons, fruits, légumes

**Comment by ChavFDG** [comment]
Normalement c'est bon, par défaut le panier s'affiche quand on a pas d'image

**Comment by JeanneVoiry** [comment]
ça ne fonctionne toujours pas

**Comment by ChavFDG** [comment]
C'est normal on a toujours rien fait dessus ;)
