### ISSUE TITLE
Blocage des mails

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#140]
Problème de blocage de mails sur plusieurs boites mails.
Piratage de notre boite mails en envoie de spam.

**Comment by dyslesiq** [comment]
Mise en place du record DNS pour SPF fait, il faudra vérifier demain que tous les mails passent bien.

**Comment by dyslesiq** [comment]
A priori c'est tout bon niveau mail, ca fait plusieurs semaines que c'est en place et pas de problèmes connus.
