### ISSUE TITLE
Ajout du système de poids variable

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#141]
[Poids variable.pdf](https://github.com/ChavFDG/Stolons/files/2122744/Poids.variable.pdf)

**Comment by ChavFDG** [comment]
Quand le producteur choisie les poids des produits et valide il faut créer des produits en vente à la pièce correspondant pour chaque valeurs et archivé le produit direct.

**Comment by dyslesiq** [comment]
Au niveau des modèles produit: on entre le poids moyen (calculé à partir des valeur de poids min et max rentrés par le producteur) dans la quantityStep en grammes(ou ml). 
Par exemple 9.5Kg => 9500 en quantity step.
Lors de l'achat, si un utilisateur commande 2 fois ce produit au poids variable, le prix est donc = 2(quantity) * QuantityStep * WeightPrice.
La quantité est gérée et affichée comme une vente à la pièce au niveau du panier (on affiche 2 pièces).

Lors du passage en période de livraison, les infos niveau BillEntry utiles seront: WeightPrice et Quantity.
Lorsque le producteur entre les poids réels de ces produits, on met à jour les BillEntry associées.
UnitPrice = poids réel * WeightPrice
Si Quantity > 1, on duplique la BillEntry associée avec les autres poids réels.

**Comment by ChavFDG** [comment]
![image](https://user-images.githubusercontent.com/16624098/44616210-e010a180-a84b-11e8-9952-2074eda4a15a.png)

**Comment by ChavFDG** [comment]
Quand on clique sur "valider" le bouton reste clickable durant l'opération. Il faudrait mettre un symbole de chargement car l'opération peut être longue.
Si l'opération se termine bien le message d'erreur apparait. Pourtant le code 200Ok est bien renvoyer.

**Comment by ChavFDG** [comment]
Quand je saisie un poids variable avec une décimal ça renvoie pas la bonne valeur au serveur.
Exemple: 
- pour "1.5" saisi , j'ai 0 reçu coté serveur
- pour "1,5" saisi , j'ai 1 reçu coté serveur

**Comment by ChavFDG** [comment]
Il ne faudrait pas pouvoir valider la récupération et le payement d'un consommateur si son panier contient des poids variable non assigné.

**Comment by JeanneVoiry** [comment]
J'ai testé la validation du paiement d'un consommateur alors qu'il contenait des poids variable non assigné.
=> il est toujours possible de valider le paiement du consommateur. C'est le prix moyen du produit au poids variable qui apparaît alors sur les factures consommateurs et producteurs.

**Comment by JeanneVoiry** [comment]
à nouveau testé aujourd'hui : 
ll est toujours possible de valider le paiement du consommateur alors que les poids variables n'ont pas été assigné. C'est le prix moyen du produit au poids variable qui apparaît alors sur les factures consommateurs et producteurs.
