### ISSUE TITLE
Gestion des stocks merdouille

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#148]
J'ai créé un produit en vente au poids avec un pallier de 100gr, stock fixe.
Je vais modifier le stock initialement à 0. J'appuie sur le + et arrivé à 0,2 il ne fonctionne plus et le message suivant apparait :
![image](https://user-images.githubusercontent.com/16624098/44627346-ac597880-a92c-11e8-8a09-9d89f4f64253.png)

**Comment by ChavFDG** [comment]
Si je change la valeur ç marche de nouveau pour 2 clicks

**Comment by dyslesiq** [comment]
C'est corrigé
