### ISSUE TITLE
Quel format d'écriture latitude/longitude ?

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#15]
En tant que producteur, quand je note mes coordonnées géographiques dans "modifier mes informations personnelles", je n'arrive pas à renseigner la latitude et la longitude (voir capture d'écran ci-dessous), quel est le format d'écriture adapté ?

![image](https://user-images.githubusercontent.com/32641097/32553034-066ceda6-c496-11e7-9b7c-43ce78d947e9.png)

**Comment by ChavFDG** [comment]
On a fait une modification hier pour que les décimaux (nombre à virgules) impose le caractère "," à la place du "." malheureusement la modification a été apporté sur la longitude et la latitude.
Le format que tu as entré est le bon en théorie. Le temps qu'on corrige il faut que tout les nombre entré sur le site le soit avec une "," pour la séparation des décimaux.
En l’occurrence :
44,737342
4,599383

**Comment by JeanneVoiry** [comment]
ok bon à savoir, 
cela explique peut-être le fait que quand je rentre un prix au kg, en étant producteur, je ne suis pas capable de noter la décimale avec la virgule mais juste avec le point... et du coup il y a plein de fois où je n'arrive tout simplement pas à ajouter un produit (quand je clique sur "ajouter", je retourne sur la page d'ajout du produit sans qu'il n'y ait un message d'erreur qui m'indique ce que j'ai mal renseigné...)

**Comment by dyslesiq** [comment]
Ca a été corrigé en même temps que les autres problèmes de chiffres à virgules.
Le format est donc bien avec des virgules.
J'ai aussi ajouté un lien vers un site qui permet de les trouver facilement (http://www.coordonnees-gps.fr/)

**Comment by JeanneVoiry** [comment]
ok tip top le site pour trouver les coordonnées plus facilement, 
par contre quand j'essaie ça ne fonctionne pas, j'ai un message qui m'indique que mes valeurs sont invalides car le format d'écriture utilise un point et non pas une virgule ! quand je mets une virgule je n'ai pas de message d'erreur

![image](https://user-images.githubusercontent.com/32641097/33420602-832320f2-d5af-11e7-8f11-11c20739b6c5.png)

**Comment by JeanneVoiry** [comment]
l'idée serait de transformer automatiquement le point en virugle
