### ISSUE TITLE
Rectification facture : gérer le cas d'un poids variable assigné

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#153]
Voir comment gérer quand un poids variable est assigné et qu'il faut le rectifier.
Exemple : 
-le producteur assigne un poulet de 1,5 kg au consommateur mais oubli de l'amener ?
- le producteur assigne un poulet de 1,5kg au consommateur mais amène un de 1,3 kg ?

Voir par une gestion via une VM regroupement bien les billEntry par consomateur / producteur.

**Comment by JeanneVoiry** [comment]
si le producteur oubli d'amener le poulet => annulation du produit sur son bon de livraison pour annulation du panier consommateur
Par contre, si le produit se trompe de poids... il faudrait pouvoir rectifier les poids variables, mais comment ?
 ce qui serait faisable, ce serait que le producteur puisse modifier ses poids variables depuis son interface personnelle tant que sa facture n'a pas été modifiée
