### ISSUE TITLE
Input des dates problème de CSS

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#156]
Problème de CSS sur l'input des dates / heures :

![image](https://user-images.githubusercontent.com/16624098/44956713-c7962c00-aec8-11e8-9f38-2a8322861f3a.png)

Affecté dans les transaction et les news.

**Comment by ChavFDG** [comment]
Réglé en partit par @dyslesiq le 02/09/2018

**Comment by dyslesiq** [comment]
C'est corrigé pour l'édition des News et des Transactions.
