### ISSUE TITLE
Indiquer site pour obtenir coordonnées GPS

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#159]
Dans l'administration d'un Stolon individuel, quand on veut changer ses coordonnées (latitude et longitude), le site http://www.coordonnees-gps.fr/ n'apparaît pas 

![image](https://user-images.githubusercontent.com/32641097/44990487-71d98680-af91-11e8-8493-185c882a8fc0.png)

Pouvez-vous l'ajouter ?

**Comment by ChavFDG** [comment]
C'est fait.
