### ISSUE TITLE
Rendre possible le téléchargement de la facture consommateur 

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#16]
En tant que consommateur, quand je vais dans "mes commandes" et que je clique sur ma commande, la facture s'affiche mais est peu lisible (se juxtapose au texte en dessous, voir photo ci dessous)

A mon avis, il faudrait un onglet "télécharger" comme dans l'ancien site.

![image](https://user-images.githubusercontent.com/32641097/32553293-c05ee732-c496-11e7-8c61-98d9e398b61a.png)

**Comment by ChavFDG** [comment]
C'est prévus et à faire ainsi que dans la gestion des paniers.
Assigné à Come. IL faut que je produise le nouveau design.

**Comment by ChavFDG** [comment]
Réalisé rapidement pour éviter de prendre du temps à Come.
A vérifier et tester.

**Comment by JeanneVoiry** [comment]
CA NE MARCHE PAS
=> "'403 forbidden" quand on clique sur "télécharger"
