### ISSUE TITLE
Bug ponctuel pour rectifier les factures

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#165]
Quand je rectifie les factures producteurs, parfois ça fonctionne, parfois non : rien ne se passe après validation de la rectification, on reste sur la même page avec le tableau des produits.
de plus , un symbole "interdit" apparaît quand je passe la souris sur le bouton "valider"

**Comment by ChavFDG** [comment]
Il faudrait mettre le truc tournant de chargement et ajouter l'affichage d'un message d'erreur en cas d'erreur.

J'ai corrigé pas mal de chose en lien avec ça dans d'autre bug. Ca devrait régler le problème. A re tester avec la nouvelle version.

**Comment by dyslesiq** [comment]
Je n'arrive pas à reproduire ce problème. Je pense que c'est le même problème quel'issue #181 et que les données de commandes sont faussées à cause du mode simulation.
