### ISSUE TITLE
Modifier graphisme tableau des rectifications

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#166]
Lorsqu'on clique sur "rectification", le tableau qui apparaît est souvent très grand et très long car beaucoup de produits.
Peut-on faire des colonnes plus étroites en écrivant le nom des produits sur plusieurs lignes ? 

+ les photos des produits ne s'affichent pas, à mon avis on peut carrément les enlever pour ne pas surcharger la page et faire ramer le site.

+ présenter les clients par ordre de numéro d'adhérents

+ présenter les produits par ordre alphabétique

**Comment by dyslesiq** [comment]
J'ai fait les petites améliorations. C'est vrai que la page n'est pas parfaite si il y a beaucoup de produits
