### ISSUE TITLE
lenteur pour que les commandes apparaissent

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#167]
J'ai passé commande depuis mon compte "jeanne.voiry@gmail.com" sur le Stolon d'Aubenas en local, puis je suis retournée sur le compte de Damien et je suis passé en mode "livraison et mise à jour des stocks",
dans la gestion des paniers de la semaine, aucune commande n'apparaît !
je reviens sur la page quelques minutes après et les commandes apparaissent enfin

est-ce juste un pb d'ordinateur ?

**Comment by ChavFDG** [comment]
Passer du mode commande au mode livraison prend plusieurs secondes, le temps d'envoyer les mails à tout les utilisateurs, de générer les bon de commandes, commandes, les pdfs ...
De plus sur l’ordinateur de test les mails sont envoyés au serveur de mail de l'ordinateur qui n'est pas démarré.
Donc le site essaie d'envoyer les mails et attends un peut avant de laisser tomber l'envoie des mails, ce qui engendre un petit temps.

Dans la pratique c'est invisible pour les utilisateurs du sites car les mails sont envoyé a un serveur de mail toujours actifs ( celui de gandi) et personne n'a le nez rivé sur midi ou minuit pour voir les commandes arriver.
