### ISSUE TITLE
poids variable : bizarrerie sur écran

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#168]
j'ai rectifié les poids variable sur stolon d'aubenas en local pour la ferme du petit poney et voilà ce qui apparaît sur mon écran 👍 
![image](https://user-images.githubusercontent.com/32641097/45040241-d49c5200-b065-11e8-88e4-c84763fdba67.png)

est-ce dû au fait que j'ai mis deux décimales à certains poids ??

**Comment by ChavFDG** [comment]
L'écran apparait comme ça quand un problème dans le code est détecté.
J'ai corrigé le problème.
