### ISSUE TITLE
arrondir à deux décimales le porte-monnaie de Stols

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#169]
Il faudrait arrondir à deux décimales la valeur du porte-monnaie en Stols.
Sur le compte de Damien dans la capture d'écran ci dessous, il y a 4 décimales

![image](https://user-images.githubusercontent.com/32641097/45078725-01e21200-b0f1-11e8-9185-7e499aad00f4.png)

**Comment by ChavFDG** [comment]
C'est fait
