### ISSUE TITLE
les commandes apparaissent tardivement

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#170]
Après avoir validé tous les paiement afin de mettre tout à zéro en local sur le stolon d'aubenas, j'ai basculé en mode "commande".
J'ai commandé depuis mon compte et le compte de Damien puis j'ai rebasculé en mode "livraison et mise à jour des stocks" .
En allant dans "gestion des paniers de la semaine" il est inscrit qu'il n'y a pas de commande. 
J'ai rafraîchi la page  plusieurs fois, je ne sais si cela est dû au fait qu'on est en local et que c'est plus lent...
5-10 minutes plus tard, les commandes apparaissent enfin!

**Comment by ChavFDG** [comment]
Voir si tu arrives à le reproduire. Il me semble que ça met arrivé. C'est du au fait qu'on est en local en mode debug. Dans ce mode quand tu passe de commande à livraison il supprime toute les factures / commandes de la même semaine. Histoire d'éviter de se retrouver avec plein de fois des commandes de la même semaine . (Dailleurs tu n'es pas obligé de tout valdier avec ce système).
Et défois on constate des effets de bord quand on passe rapidement de mode a un autre.

**Comment by JeanneVoiry** [comment]
ok 
mais dans ce cas, comment je fais des simulations si les commandes ne s'affichent plus ?

**Comment by ChavFDG** [comment]
Ha mais là ca ne marche plus du tout du tout ? Tu est repassé en commande puis livraison puis commande, en laissant quelques secondes entre ?
As tu relancer en faisant carré rouge puis triagle vert ?

**Comment by JeanneVoiry** [comment]
bizarre ça a refonctionné quand j'ai rééteint puis réallumé mais à mon avis
il faut que tu testes toi mm ce soir!

**Comment by ChavFDG** [comment]
Tester non reproduisible
