### ISSUE TITLE
Pas de mise à jour du tableau de rectification des livraisons suite à annulation d'un panier consommateur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#171]
Quand on annule un panier consommateur (dans l'exemple ci dessous, le panier de Damien n°2), les produits concernés disparaissent bien automatiquement du bon de commande du producteur.
Or, si on souhaite modifier ce bon de commande, les produits annulés apparaissent dans le tableau de rectification.
Voir ci dessous une capture d'écran du bon de commande à jour et une capture d'écran du tableau de rectification de la facture qui comprend deux ailes de poulet en trop par rapport au bon de livraison actualisé.

**bon de commande à jour** 

![image](https://user-images.githubusercontent.com/32641097/45081924-871cf500-b0f8-11e8-9a71-0432b9ed955a.png)

**Tableau de rectification pas à jour**

![image](https://user-images.githubusercontent.com/32641097/45081995-aa47a480-b0f8-11e8-8eff-29c200266396.png)

=> les produits de Damien (censés être annulés) apparaissent toujours !

**Comment by ChavFDG** [comment]
Je l'ai ai enlever. Par contre si tout a était annuler pour un producteur ça fais ça :
![image](https://user-images.githubusercontent.com/16624098/45084677-3230ad00-b0ff-11e8-9a3c-ab87342ad063.png)
