### ISSUE TITLE
Problème concordance facture consommateur avant/après rectification livraison d'un producteur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#172]
Pour la semaine 36 sur Stolon Aubenas en local, j'ai d'une part annuler la commande de Damien (n°2) puis j'ai modifié la livraison de la ferme des petits poney en enlevant un poulet entier au client n°1 (moi-même)

Or, la facture consommateur du client n°1 n'est plus cohérente suite à cette rectification de livraison.

Avant la rectification, voici la facture conso

![image](https://user-images.githubusercontent.com/32641097/45083390-fd6f2680-b0fb-11e8-91bb-b07141657be0.png)

Après la rectification, voici la facture conso

![image](https://user-images.githubusercontent.com/32641097/45083440-21326c80-b0fc-11e8-8483-01e907b5ebc9.png)

Seuls les produits de la ferme des petits poney s'affichent ! et pas les autres produits commandés aux autres producteurs... bizarre

De même, mon panier affiche le mauvais montant 
![image](https://user-images.githubusercontent.com/32641097/45083539-59d24600-b0fc-11e8-9147-a11b0ff84b09.png)

Or, dans la liste des producteurs ayant à livrer, je suis la seule consommatrice mais le montant que je dois payer (8,90) est largement inférieur à la somme de tous les montants dus aux producteurs

![image](https://user-images.githubusercontent.com/32641097/45083604-930ab600-b0fc-11e8-865d-bbc1817f3d0e.png)

**Comment by ChavFDG** [comment]
Pfiou, c'est corrigé.
