### ISSUE TITLE
Améliorations graphiques page de présentation d'un stolon

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#173]
sur la copie d'écran ci dessous, je verrai bien l'espace s'agrandir là où les flèches partent vers l'extérieur et se réduire un peu là où les flèches partent vers l'intérieur.
![image](https://user-images.githubusercontent.com/32641097/45084146-d6b1ef80-b0fd-11e8-8091-7dbc264b0168.png)

de plus, je pense qu'il vaut mieux écrire "horaires de récupération des paniers" plutôt que "horaires paniers"

Idem  , laisser un espace entre "les produits" et la liste des produits qui s'affichent

**Comment by ChavFDG** [comment]
C'est fait
