### ISSUE TITLE
impossible de saisir les poids variables

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#174]
j'ai fait un test de commande sur Stolon test en commandant des produits au poids variable à la ferme du petit poney.
quand je me connecte sur le compte de la ferme et que je vais dans "mes produits et mes stocks", sans avoir valider leur livraison, je clique sur "saisir les poids variable" et rien ne se passe

**Comment by dyslesiq** [comment]
L'ajout des nouvelles tables dans les "include" de la requête BDD pour les données des produits poids variable faisait partir en récursion infinie EntityFramework. Les données n'arrêtaient pas d'être envoyée, et la condition de début d'affichage de la fenêtre est lorsque les données sont toutes arrivées donc rien ne se passait.
AsNoTracking() FTW.

**Comment by ChavFDG** [comment]
Rho bien jouer ! On l'oubli tout le temps le AsNoTracking !!!!
