### ISSUE TITLE
Meilleure gestion de la suppression d'un utilisateur

### ISSUE THREAD

**Issue by dyslesiq** [ChavFDG/Stolons#175]
* Filtrer les utilisateurs "Deleted" dans le choix pour le changement de stolons
* Après la suppression de l'utilisateur depuis un stolon, mettre la valeur du dernier stolon auquel il s'est connecté à null

**Comment by ChavFDG** [comment]
On affiche maintenant uniquement les stolon d'où l'utilisateur n'a pas été supprimé.
