### ISSUE TITLE
bug pour accéder à son compte stolon

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#177]
Céline VENOT est inscrite sur Stolon Test2 et Stolon de Privas avec l'adresse mail suivante : 
celine_venot@hotmail.fr 
Or, quand elle se connecte elle arrive directement sur Stolon Test2 et impossible d'accéder au Stolon de Privas !

**Comment by ChavFDG** [comment]
C'est réglé pour Madame Venot :).
Le bug est corrigé il faudra bien tester.
