### ISSUE TITLE
erreur factures producteurs quand on ne saisit pas les poids variables

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#179]
j'ai volontairement omis de saisir les poids variable sur stolon test (producteur : Jeanne VOIRY, produit vendu au poids variable : escalope de veau)

puis j'ai validé la livraison, le paiement du consommateur et le paiement de la facture prod.
Voici la facture producteur 

![image](https://user-images.githubusercontent.com/32641097/45361754-4da22900-b5d3-11e8-9f3e-0a74e283b42a.png)

=> comment est choisi le poids quand le producteur ne l'a pas renseigné ?

dans le cas de la capture d'écran, le poids indiqué est de "2,301 kg"=> une décimale de trop.
Le prix HT est de 8,51 € => à quoi correspond-il ? en effet, l'escalope est vendue 3€ du kilo, le prix HT devrait donc être de 6,54 €;

le total HT est de 19570,01 € => erreur !!!

Je propose que lorsque le producteur oublie de renseigner le poids variable et que sa livraison est validée ou que le paiement de la facture consommateur est validée => il est automatiquement utilisé dans la facture conso et la facture producteur le poids et le prix moyen du produit.

De plus, le prix et poids de l'escalope qui apparaissent sur la facture producteur ne sont pas les mêmes que ceux qui apparaissent sur la facture consommateur

![image](https://user-images.githubusercontent.com/32641097/45362143-4d565d80-b5d4-11e8-8410-07c090834c35.png)

dans le cas présent : l'escalope est indiquée à son poids et prix maximal (prix unitaire de 9 € qui correspond à 3€ le kg pour 3 kg commandé, le poids maximal de l'escalope qui a été renseigné par le producteur).

**Comment by ChavFDG** [comment]
Que ce passe t'il si le producteur ne livre pas / oubli de renseigner ces poids variable et qu'on valide le consommateur ? Il doit payer ?
Ne devrait ont pas empêcher le validation/payement d'un panier consommateur en lien avec un producteur n'ayant pas livré ou saisie ces poids variable. ( de manière à obliger de passer par l'outil informatique).
Dans ce cas le bénévole devra aller modifier / annuler la livraison du producteur.

**Comment by JeanneVoiry** [comment]
Si le producteur a oublié de renseigner le poids variable, c'est le poids moyen qui s'affiche par défaut 
Deux options possibles : 
- on prend le poids moyen pour la facture consommateur et la facture producteur
PB : ça peut être injuste pour le consommateur qui peut être amené à payer plus que la valeur réelle du produit.

- si accès au poids réel du produit, on recalcule la facture consommateur en conséquence et on saisit par la suite le poids variable sur le site, en veillant à ne pas valider la livraison producteur trop vite.
PB : peu probable que les producteurs écrivent le poids de leur viande.

**Comment by ChavFDG** [comment]
Si un producteur n'a pas livré on fait une rectification de poids variables avant la venu du consommateur.
