### ISSUE TITLE
Erreur d'affichage dans la page "Mon panier"

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#18]
Au niveau de la page "Mon panier" ( Views/WeekBasket/Index), il y a des problèmes d'affichages. Il faudrait re-tester avec plusieurs résolution et % de vue.

Exemple en 1980x1024 et 125% de texte :
![image](https://user-images.githubusercontent.com/16624098/32596833-f9d51600-c534-11e7-9e02-9b816acfc9e4.png)
Ce qui donne :
![image](https://user-images.githubusercontent.com/16624098/32596856-08270092-c535-11e7-9e73-dbf137236711.png)

Problème de centrage et réduction des vignettes de produits.

On peut aussi avoir :
![image](https://user-images.githubusercontent.com/16624098/32596897-284ea4ec-c535-11e7-89c0-bb8deb7f59e8.png)

Superposition du panier flottant avec les produits et le menu en haut.

**Comment by JeanneVoiry** [comment]
résolu
