### ISSUE TITLE
rendre impossible l'annulation d'un panier quand les livraisons producteurs sont confirmées

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#180]
j'ai fait le test de valider toutes les livraisons des producteurs et de valider le paiement de leurs factures puis j'ai annulé un panier consommateur.
=> l'annulation du panier qui est faite a posteriori des validations des livraisons et paiements factures producteurs ne peut justement pas être répercuté sur ces bons de livraisons et factures !!

=> pour éviter cette erreur, je pense qu'il faut rendre impossible l'annulation d'un panier consommateur (avec une croix grisée par exemple), une fois que les bons de livraisons producteurs ont été validé !!!

**Comment by ChavFDG** [comment]
@JeanneVoiry A l'heure actuelle quand on annule un panier d'un consommateur en lien avec un producteur ayant déjà livré, la facture du producteur n'est pas modifier.
Quand on clique sur annulé un panier ce message apparait :

>  Annuler le panier entrainera la modification en conséquent des factures producteurs concernées excepté si ces derniers ont déjà livré leurs produits. Dans ce cas leurs produits leurs seront dus
> 
> Confirmer vous l'annulation du panier ?

Voir l'issue #158 .
