### ISSUE TITLE
bug dans la rectification de la livraison

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#181]
quand je clique sur "rectifier la livraison"
voici la capture d'écran

![image](https://user-images.githubusercontent.com/32641097/45364043-71686d80-b5d9-11e8-882b-450190db3eff.png)

ce n'est pas logique que les stocks soit équilibré quand le total des caisses de poires fait 4 et que l'unique cliente en a commandé une seule !!!

**Comment by ChavFDG** [comment]
@dyslesiq voir sur stolons.org dans Stolon de Test. Toute les "Rectifier la livraison" ont ce symptôme.

**Comment by ChavFDG** [comment]
@dyslesiq en cliquant sur la commande de Jeanne il apparait qu'elle a été annulé. Peut être une mauvaise mise à jour ou envoie des donnés cotés rectification, j'investie et mais à jour l'issue

**Comment by dyslesiq** [comment]
Je pense que ce n'est pas lié à la correction de la livraison mais aux billEntrys qui restent et qui faussent les entrées

**Comment by ChavFDG** [comment]
Après test ça ne le fait pas. Il faudrait voir si ça a pas été mis à jour mais pas encore pusher sur le serveur.

@JeanneVoiry Re faire le test pour voir si le bug persiste.

**Comment by JeanneVoiry** [comment]
j'ai refait le test et le bug a disparu
