### ISSUE TITLE
URGENT impossible d'accéder au site pour certains clients !

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#183]
Le client du Stolon d'Aubenas, Gérard Dugué me dit qu'il n'arrive pas à se connecter au site depuis 3 semaines !!
je lui ai conseillé de changer de moteur de recherche pour voir, voici ce qu'il me répond : "    Bonjour,

   Je viens de faire un essai à l’aide de « Safari »…   En vain. La connexion au site est aussi inaccessible.  Le problème concerne également d’autres clients.

                                 Avec mes remerciements anticipés pour votre aide précieuse

                                                                                                                                      G. D.
"
Pouvez vous regarder ??

son adresse mail est g.dugduranc@orange.fr

**Comment by ChavFDG** [comment]
Voit si il rentre bien www.stolons.org et pas aubenas.stolons.org
Car un autre adhérent d'aubenas a eu le problème. (bien que aubenas.stolons.org marche)

**Comment by JeanneVoiry** [comment]
Xavier le producteur de picodon n'arrive pas à se connecter au site !
Benoit me dit que parfois quand il essaie de se connecter chez lui ça lui met "adresse introuvable"

**Comment by dyslesiq** [comment]
C'est corrigé.
En fait nous avions enlevé ce qu'on appelle les "sous-domaines" "privas" et "aubenas" associés au domaine stolons.org pensant que les utilisateurs iraient naturellement à stolons.org ou www.stolons.org

J'ai donc réactivé ces adresses mais... c'est un montage qui se voulait temporaire et je pense que le mieux serait qu'il le reste.
Il faudrait sans doute écrire un mail aux adhérents leur demandant d'accèder au site via www.stolons.org directement, puis d'ici quelques semaines désactiver "privas" et "aubenas". Les certificats SSL pour privas et aubenas seront valides jusq'à début décembre 2018 (ce qui causera alors une exception de sécurité dans le navigateur).

Maintenant que c'est en place ca ne pose pas de problème mais c'est une gestion pas si évidente si l'on doit ajouter manuellement tous les sous-domaines associés à la localité des stolons hébergés sur stolons.org.
(Je dis cela en pensant à d'éventuels futurs stolons qui voudraient pour accèder à leur instance par xxx.stolons.org, tutu.stolons.org,....)

Si c'est quelque chose que l'on veut on pourra en parler plus en détail, quitte à automatiser cette gestion si besoin.
