### ISSUE TITLE
Erreurs sur factures producteurs

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#187]
Dans "panier de la semaine"
dans "producteur en attente de paiement"
le prix de la facture qui s'affiche à côté de la commission entre parenthèse n'est pas le même que le prix qui s'affiche dans la facture quand on l'ouvre !!

=> en faisant le calcul, je trouve que c'est le prix qui s'affiche sur la page des producteurs en attente de paiement qui est juste = le prix qui s'affiche à côté de la commission entre parenthèses.

+ autre erreur,  dans le détail de la facture producteur, la commission est de zero !

**Comment by ChavFDG** [comment]
J'aurais besoin de savoir de quel Stolon on parle et quelles factures ?
J'ai regarder su Privas et le prix affiché sur la page est le même que le "Net à payer" de la facture.
Pareil chez Aubenas.

Exemple : 
Sur la page :
![image](https://user-images.githubusercontent.com/16624098/45587077-c7eaea00-b900-11e8-814c-322ebb087689.png)

Sur la facture :
![image](https://user-images.githubusercontent.com/16624098/45587068-b43f8380-b900-11e8-8946-cc1d3df311eb.png)

**Comment by JeanneVoiry** [comment]
Pour la facture de la Clémenterie semaine 38, dans le détail on a montant net à percevoir : 20,71 €

![image](https://user-images.githubusercontent.com/32641097/45667749-bb41de00-bb1a-11e8-95c9-e5be628fb52a.png)

Or, dans le récap des factures en attentes de paiement,
on a le montant 21,80 € pour la clémenterie 

![image](https://user-images.githubusercontent.com/32641097/45667805-de6c8d80-bb1a-11e8-8539-8acdaa3bead7.png)


=> c'est le prix sans la commission qui s'affiche dans le récap des factures en attente de paiement.

c'est bizarre car quand j'avais repéré ce bug (pas le même prix affiché dans la liste des producteurs en attente de paiement et dans le détail de la facture), le "mauvais prix" qui s'affichait n'était pas le prix sans la commission. Dans les factures en attente de paiement de cette semaine (semaine 38), c'est le cas.

**Comment by JeanneVoiry** [comment]
ça a l'air de marche maintenant
