### ISSUE TITLE
URGENT Bug courriels à tous les adhérents

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#188]
quand j'essaie d'envoyer un courriel à l'ensemble des consommateurs 
le message d'erreur : 504 gateway time-out apparaît
mais quand j'ai fait "envoyer à tous les adhérents" ça a fonctionné (je l'ai bien reçu dans ma boite mail)
par contre il s'affiche sur le site "SUCCES : Les courriels aux 0 utilisateurs ont été envoyé avec succès" => il faudrait renseigner le nombre de mails envoyer !

**Comment by dyslesiq** [comment]
Salut! Je viens de recevoir le mail deux fois. Apparement l'envoi marche. C'est au bout de combien de temps que tu as cette erreur ?

**Comment by JeanneVoiry** [comment]
par contre je l'ai reçu en plusieurs fois, est-ce normal ?!

**Comment by ChavFDG** [comment]
On a corrigé ça. Le problème venait du fait que le temps d'envoi de tout les courriels étaient plus long que le temps d'attente de la réponse du navigateur au serveur ( le timeout).
Pour cela on envoi les courriel dans un thread séparé et on affiche maintenant le nombre de mail envoyé.

De plus maintenant on envoi uniquement les mails aux adhérent ayant coché la case "information importante". 
Dans le cas d'un envoi de mails uniquement aux producteurs la case n'est pas prise en compte. Tout les producteurs recevrons le mails.
