### ISSUE TITLE
Ajout de la fonction de validation/modification d'un bon de commande

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#19]
Ajout de la fonction de validation d'un bon de commande. 
On a envoyé un bon de commande, quand le producteur arrive si il y a une erreur on peut modifier l'erreur et valider pour éditer la facture définitive.

**Comment by dyslesiq** [comment]
On peut déjà avoir un apercu de ce qui a été fait dans 'Gestion des paniers' puis 'réctifier la livraison'.
Il reste à coder la validation des modèles, l'affichage des erreurs, l'ajout de la textarea 'raison' et l'envoi des modifications au serveur.

Par contre petit problème d'affichage potentiel: si le producteur a eu des commandes pour beaucoup de produits différents (>7), le tableau ne s'affichera pas en entier et sera de toutes facons trop large.

Deux solutions:

- mettre en place un scroll horizontal, et scroller à droite pour voir les produits si ils sont trop nombreux.
- Avant d'afficher cette pop-up, choisir les produits à réctifier (qui ne seront jamais plus de 2-3 j'imagine).

**Comment by ChavFDG** [comment]
Ca peut en effet poser des problèmes cette histoire de tableau trop large. En plus on le fait apparaitre dans une pop up ?

**Comment by ChavFDG** [comment]
Il faut maintenant faire apparaitre le fait qu'une commande est été modifié coté consommateur et producteur et envoyer un mail pour prévenir.

**Comment by JeanneVoiry** [comment]
j'ai testé la fonction de rectification d'une livraison sur de nouvelles factures en local sur stolon de privas : 
quand on clique sur "rectifier la commande", rien ne se passe.

**Comment by ChavFDG** [comment]
Ajout d'un sablier quand on clique sur "valider" car la fonction est un peut longue et si on est pas patient et qu'on clique plusieurs fois elle s'exécute plusieurs fois.

**Comment by ChavFDG** [comment]
1)Quand je clique sur "rectifier la livraison" j'ai ça : 
![image](https://user-images.githubusercontent.com/16624098/44629080-598eb980-a94a-11e8-8fb9-bd68572d43db.png)
Il me semble que c'était du au script pas bien chargé.

2) Il faudrait voir le comportement des poids variable lors de la rectification de la livraison avant et après assignation de produits.
Avant pour le cas ou le producteur ne les a ni assigné ni livré 
Après pour le cas ou il les a assigné mais oublié certain / c'est trompé.

**Comment by JeanneVoiry** [comment]
bug au niveau de l'affichage des produits à rectifier quand l'offre de produits est importante cf capture d'écran des produits de Jehan Royé, maraicher au stolon d'aubenas 

![image](https://user-images.githubusercontent.com/32641097/45751081-895f7300-bc11-11e8-8e11-170f1235dd0b.png)

**Comment by JeanneVoiry** [comment]
toujours un bug,

quand je clique sur "rectifier la livraison" rien ne s'affiche.

**Comment by ChavFDG** [comment]
@nmichon si tu peux regarder s'il te plait
