### ISSUE TITLE
Courriels ne s'envoient pas

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#197]
J'ai essayé d'envoyer un courriel aujourdhui le 25 septembre depuis le Stolon d'Aubenas à l'ensemble des adhérents et je n'ai rien reçu (pas même dans ma boîte spam)

J'ai essayé depuis le Stolon test de l'envoyer uniquement aux producteurs => il s'envoie et affiche le nombre de courriels envoyés, je l'ai bien reçu dans ma boîte mail
Mais ça ne marche pas quand je l'envoie à tous les consommateurs ou à l'ensemble des adhérents

**Comment by dyslesiq** [comment]
Hello, tu aurais l'heure exacte à laquelle tu as essayé d'envoyer les mails stp ?

**Comment by JeanneVoiry** [comment]
c'était entre 11h et 11h30, je n'en sais pas plus!

**Comment by JeanneVoiry** [comment]
si ça remarche d'ici ce soir je veux bien que tu me dises pour que j'envoie un dernier rappel pour l'événement au stolon d'aubenas demain soir!

**Comment by dyslesiq** [comment]
Ok merci! c'est pour trouver plus facilement des traces de l'erreur. j'essaie de regarder ca cet aprem

**Comment by ChavFDG** [comment]
ce Bug ne s'est pas reproduit depuis plusieurs mois
