### ISSUE TITLE
Référencement dans Google

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#198]
Un vendeur d'Ikoula m'a dit : 
"Petit conseil sur votre site stolons.org
Attention vous n'avez pas fait de redirection de stolons.org vers www.stolons.org > donc attention google vous pénalise dans le référencement avec du duplicate content"

=> de plus, par rapport au référencement sur Google, on est visible seulement à la 2ème page sous le onm "Index Stolons"
=> peut-on enlever le "Index" ?

**Comment by dyslesiq** [comment]
J'ai mis en place la redirection de stolons.org vers www.stolons.org.
Pour le reste il faudrait trouver un titre et des mots clé qui apparaissent dans les résultats et améliorent le référencement (par exemple panier bio, commandes bio en ligne, etc)

**Comment by JeanneVoiry** [comment]
liste de mots clés pour le référencement dans Google : 

stolons
panier bio local
drive bio local
circuits courts
alimentation bio locale
manger bio et local
producteurs bio
agriculture biologique
Agri Bio Ardèche

**Comment by dyslesiq** [comment]
J'ai ajouté les mots clés.
@JeanneVoiry Il faudrait aussi mettre un titre et une description (qui au mieux content quelques mot-clés aussi).

![screenshot_2018-10-09_18-22-52](https://user-images.githubusercontent.com/13435669/46683563-d02d0100-cbf0-11e8-9eb2-a4b57af90ad9.png)

Ce sont les propriétés qui s'affichent directement dans les résultats des moteurs de recherche et ça doit être assez accrocheur en général (comme ici les 2 flèches)

Pour l'instant j'ai mis comme titre 

> Stolons - Commande en ligne de produits bio et locaux

et comme description:

> Stolons est un outil à but non lucratif de commandes hebdomadaires de produits certifiés de l'agriculture biologique provenants de moins de 50 km du lieu de dépôt. Et si on mangeait Bio et Local ?

**Comment by JeanneVoiry** [comment]
Pour le titre : Stolons - Et si on mangeait bio et local ?

Pour la description : 
Commandez en ligne vos produits 100% bio et locaux sur stolons.org, un outil innovant à  but non lucratif de commandes hebdomadaires développé par Agri Bio Ardèche.

**Comment by dyslesiq** [comment]
C'est fait depuis quelques temps.
