### ISSUE TITLE
Impossible de supprimer un produit

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#200]
Quand je suis en période de mise à jour des stocks, sur le Stolon test, avec mon compte (jeanne.voiry@gmail.com), je n'arrive pas à supprimer mes produits "basse côte boeuf" et "escalope de veau"

![image](https://user-images.githubusercontent.com/32641097/46273470-e33b3380-c555-11e8-96bd-93f01fd4d0f9.png)

**Comment by dyslesiq** [comment]
Un produit de peut pas être complètement supprimé à partir du moment ou il y a au moins une commande (cela permet de garder les infos dans l'historique des commandes). Dans ce cas il faut l'archiver.
