### ISSUE TITLE
l'annulation d'un panier ne se répercute pas sur le montant total des recettes 

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#203]
Pour la semaine 40, dans STOLON test, le montant total des recettes est de 198,90 €

![image](https://user-images.githubusercontent.com/32641097/46343614-ad25ae80-c63e-11e8-9916-85f49938ea53.png)

Or, quand on annule un panier consommateur, et qu'on valide les livraisons et le paiement de toutes les factures, le montant TTC des recettes de la semaine 40 indiqué dans l'onglet "historique" n'est pas mis à jour.

**Comment by ChavFDG** [comment]
Les paniers consommateurs annulés après la validation de la livraison d'un producteur n'affectent pas les factures producteurs. En effet ces dernier ayant valider on doit leurs payer leurs factures.
C'est au stolon de gérer le cas des consommateurs annulant leurs paniers après livraison.
(Exemples : rachat du panier par l'asso, par un autre consommateur, proposition d'un autre date, faire payer quand même ...)
