### ISSUE TITLE
ajouter la mention "en conversion vers l'agriculture biologique"

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#204]
ajouter la mention "en conversion vers l'agriculture biologique"
dans la liste des logo

**Comment by ChavFDG** [comment]
On met quoi comme logo pour "en conversion vers l'agriculture biologique" ?

**Comment by JeanneVoiry** [comment]
tout compte fait comme il n'y pas de logo existant, je pense que c'est mieux que le producteur écrive lui-même la mention "produit en conversion vers l'AB" dans le titre de son produit.
