### ISSUE TITLE
BUG URGENT : le récap des commandes de la semaine au Stolon d'Aubenas ne s'affiche pas!!

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#206]
voilà ce qui apparaît quand on clique sur aperçu des factures ou quand on essaie de la télécharger 

![image](https://user-images.githubusercontent.com/32641097/46417345-b8093d80-c729-11e8-9cac-bb3e58e38d9e.png)

**Comment by JeanneVoiry** [comment]
ce bug s'est réitéré la semaine dernière

**Comment by ChavFDG** [comment]
N'ai plus reproduit depuis plusieurs mois
