### ISSUE TITLE
Affichage des WebAdmins dans la gestion des adhérents

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#21]
Dans la gestion des adhérents et de leurs roles (RoleActions.cshtml) il faudrait ajouter la possibilité de voir si l'adhérent est un web admin ou non.
Pour cela ajouter à coté de  ![image](https://user-images.githubusercontent.com/16624098/32602825-e1625f84-c547-11e7-8ccd-dcc2bc3aa329.png) un symbole ( ![image](https://user-images.githubusercontent.com/16624098/32602856-fd593a50-c547-11e7-88d1-f111086e58eb.png) par exemple class="glyphicon-leaf") et quand on passe la souris dessus afficher le message "Ce membre est administrateur web".
Les changements sont à effectué dans **RoleActions.cshtml** ligne 45

**Comment by dyslesiq** [comment]
C'est en place depuis un moment, je ferme.
