### ISSUE TITLE
impossible de supprimer compte adhérent qui a déjà payé cotisation

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#217]
cf mail de Catherine du Stolon de Privas :

Un des adhérent consommateur n'arrive plus à accéder à son compte depuis qu'il en a modifié l'adresse mail depuis le site : 
Il s'agit du compte n°157 au nom de Laeticia Pellerey. J'ai vu son conjoint hier, et il m'a dit avoir essayé de faire la récupération de mot de passe, mais cela indique un message d'erreur, ou bien n'envoie pas de message, ni à la nouvelle ni à l'ancienne adresse mail utilisée.

J'ai donc proposé de supprimer son compte pour en créer un nouveau, mais son compte ne peut être supprimé du fait que la cotisation pour cette année a été payée. Et malheureusement, je ne peux pas non plus créer de nouveau compte parce que l'adresse mail est la même !

Voilà les coordonnées de la personne : 
Laeticia Pellerey
airsiss@gmail.com
0613021263

**Comment by ChavFDG** [comment]
C'est réglé
