### ISSUE TITLE
bug affiche validation panier

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#218]
sur le stolon de privas, j'ai commandé un panier et je l'ai bien validé
par contre ça affiche en haut à droite de l'écran que le panier n'est pas validé !
![image](https://user-images.githubusercontent.com/32641097/46944509-8326b000-d072-11e8-9e95-bf15887d4998.png)

j'ai quand même reçu le mail de confirmation de commande

**Comment by ChavFDG** [comment]
Après avoir rafraichi la page été t'il toujours non validé ?

**Comment by JeanneVoiry** [comment]
je pourrai te répondre si ça m'arrive à nouveau une prochaine fois !

**Comment by JeanneVoiry** [comment]
en stand by car ça ne m'est pas à nouveau arrivé !

**Comment by ChavFDG** [comment]
Ce bug ne c'est pas reproduit depuis plusieurs mois.
