### ISSUE TITLE
Ajouter contacts du Stolon dans les mail en cas d'annulation de panier

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#222]
Dans le cas où un client souhaite annuler son panier, il ne sait pas comment s'y prendre (aucune info mentionnée à ce sujet sur le site)

=> je propose de rajouter dans les deux mails que reçoit le consommateur (mail à la fin période de commande et mail de rappel le jour de la distribution) le message suivant : 

"Pour annuler votre commande, merci de nous prévenir au moins 24h à l'avance :
contacts : [indiquer les numéro de téléphone entrés sur le site du Stolon]"

**Comment by ChavFDG** [comment]
C'est fait sauf pour le mail du jour de la distribution car il y avait déjà ça :
"En commandant en ligne sur notre site, vous vous engagés à venir chercher votre panier.<En cas d'indisponibilité, veuillez nous prévenir au plus tôt au ... "
