### ISSUE TITLE
ajouter onglet "contact" sur compte stolon

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#223]
les consommateurs sont souvent perdus lorsqu'il s'agit de contacter leur stolon
=> en général ils se tournent vers la messagerie ou m'appelle.

a mon avis, il faudrait ajouter un onglet "contact" dans la barre de menu, qui précise les numéros de tél et le courriel du Stolon !

**Comment by ChavFDG** [comment]
Modification faite mais si le stolon n'a pas rentré son numéro de téléphone il n'y aura que le mail et l'adresse qui s'affiche.
