### ISSUE TITLE
message d'erreur quand modification raison sociale d'un producteur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#229]
quand je modifie la raison sociale d'un producteur, le message suivant d'erreur apparaît : 

![image](https://user-images.githubusercontent.com/32641097/48199303-fcf14700-e35b-11e8-8186-3fe9e14e1aaf.png)

le nom de la ferme est bien modifié, par contre la photo disparaît du profil producteur ! 
=> bug repéré sur Stolon test sur tous les producteurs

**Comment by ChavFDG** [comment]
Après test ça fonctionne.
