### ISSUE TITLE
supprimer vente "emballé"

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#232]
dans les choix de type de vente on a l'option "emballé", je pense qu'il faut la supprimer car personne ne sait à quoi ça correspond et personne ne s'en sert.

**Comment by ChavFDG** [comment]
Il faudrait expliquer cette fonctionnalité plutôt que supprimer une fonctionnalité qui marche :)
Peut être rajouter des informations dans la saisie des produits ?

Pour info la vente emballé fonctionne comme la vente au poids à la différence que le produits est conditionné emballé plutôt qu'en vrac. C'est le cas par exemple d'un fromage à la coupe qui serait pesé avec une balance ML et ensuite emballé.

**Comment by ChavFDG** [comment]
C'était prévus pour le cas d'un vraie emballage. Pas juste un papier. Cas ou le produit a besoin d'un emballage spécifique pour des questions de normes.

**Comment by JeanneVoiry** [comment]
tu veux dire que si le producteur choisit vente "emballé", il devra renseigner d'autres infos ? car pour l'instant, la vente au poids et la vente de produit emballé sont les mêmes !

Le producteur est responsable de ses produits et peut inscrire ce qui est important dans la description de ces produits, je pense que c'est plus simple comme ça.

**Comment by JeanneVoiry** [comment]
vu avec Benoit : la vente de produit "emballé" est à supprimer
