### ISSUE TITLE
Impossible d'ajouter une nouvelle

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#237]
On ne peut pas ajouter de nouvelle depuis microsoft edge

![image](https://user-images.githubusercontent.com/32641097/48544433-e0a55b00-e8c3-11e8-9a4f-106f8b1e5939.png)

En effet, dès qu'on essaie d'entrer les horaires, la date s'efface.

**Comment by ChavFDG** [comment]
Apparemment sous Google Chrome aussi, à tester.

**Comment by JeanneVoiry** [comment]
sur Google chrome aussi ça ne fonctionne pas

en fait ça ne marche que sur mozilla j'ai l'impression.

Pouvez-vous y faire quelque chose ?
ça fait déjà 3 producteurs qui me posent la question

**Comment by dyslesiq** [comment]
C'est corrigé et testé sous chrome. Je pense que ca passera sur tous les navigateurs maintenant.
