### ISSUE TITLE
Vérifier le système des calculs des cotisations

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#24]
Vérifier le système des calculs des cotisations. En outre le système du mois / demi mois ?

**Comment by ChavFDG** [comment]
Quelle système de cotisation faut il mettre ne place ?
Pour l'instant on peut choisir d'avoir ou non une cotisation.
Si on a une cotisation elle est automatiquement à l'année. On peut juste dire qu'à la moitié de l'année la cotisation est diviser par deux.
Quelle autre solutions système faut il mettre en place ?

**Comment by JeanneVoiry** [comment]
Réponse de Benoît : La politique d'adhésion dépend des statuts de l'asso. pour nous c'est une année civile pour l'instant. Chaque asso locale devra choisir sa politique. Donc ne rien préciser à ce sujet

**Comment by ChavFDG** [comment]
A l'heure actuelle le site permet de mettre en place un système de cotisation ou non.
Dans la cas ou le système de cotisation est activé on choisie le mois de départ des cotisations. Cela permet de réinitialiser automatiquement les cotisations lors du mois choisie. 

Exemple je créer une structure je choisi mois de départ des cotisations à janvier. Tout les janvier la cotisation est réinitialisé.

Ce système est il bon ?

**Comment by JeanneVoiry** [comment]
est-ce que le système de cotisation sera modulable par la suite en fonction des décisions de l'asso locale ?

**Comment by ChavFDG** [comment]
Les seuls options modulable sont :
- Avec/sans cotisation
(Si avec)
- Mois de départ de la cotisation ( réinitialisation automatique lors du 1er du mois)
- Montant de la cotisation ( producteur / consommateur / sympathisant)
- Mode 50% de la cotisation à la moitié de l'année oui/non

**Comment by Benoitab07** [comment]
yo,
ok pour cotisation par année complète avec possibilité de demi année ;
inscrire date de début de l'année prise en compte (ex : aubenas c'est de juin à mai)
a+

**Comment by ChavFDG** [comment]
Maintenant on affiche dans la gestion des adhérents les informations sur les cotisations : 
![image](https://user-images.githubusercontent.com/16624098/42757129-15957d4c-88ff-11e8-8845-8aed2f0af323.png)
