### ISSUE TITLE
bug rectification des livraisons

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#242]
Sur stolon test, quand j'essaie de modifier le total des boite d'oeuf, je clique sur diminuer le stock, on passe directement de 2 à 0.... or il faudrait passer de 2 à 1

https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLhklcdXzWNlzKwWxWKnFNMxD

**Comment by dyslesiq** [comment]
Je ne reproduis pas ce problème. Il a potentiellement été corrigé suites aux modifications sur les rectifications de livraison la dernière fois.
