### ISSUE TITLE
rectification message de récupération des paniers

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#243]
dans le message de rappel de récupération des paniers de Stolon de Privas, la phrase n'est pas finie car le Stolon n'a pas indiqué de numéro de téléphone : 

"Rappel Stolon de Privas : panier à récupérer aujourd'hui
Votre panier est disponible tous les jeudi entre 17h30 et 19h au local de l'association.
En commandant en ligne sur notre site, vous vous engagés à venir chercher votre panier.
En cas d'indisponibilité, veuillez nous prévenir au plus tôt au "

je propose de juste écrire "en cas d'indisponibilité, veuillez nous prévenir au plus tôt."

**Comment by ChavFDG** [comment]
J'ai ajouter une condition. Si le numéro est renseigné on fait comme avant, si il ne l'ai pas on met :  "en cas d'indisponibilité, veuillez nous prévenir au plus tôt."
