### ISSUE TITLE
URGENT - bug sur contact@stolons.org

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#245]
hier le 6/12/2018, j'ai par erreur créé deux fois le stolon de rosières depuis le compte contact@stolons.org
après avoir supprimer un des deux stolons créés, j'atterris sur une page blanche 
![image](https://user-images.githubusercontent.com/32641097/49633568-11c40780-f9fa-11e8-9f29-1007b15440a0.png)

et je n'arrive plus à me connecter avec l'adresse contact@stolons.org
par contre, pas de souci avec un autre compte

**Comment by ChavFDG** [comment]
On c'était retrouver avec contact@stolons.org qui avait un adhérentStolon sans stolon assigné. J'ai corrigé les problèmes engendrais mais normalement ce cas ne devrait pas avoir lieu
