### ISSUE TITLE
URGENT - ajouter bouton de régénération des factures depuis compte administrateur d'un stolon

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#248]
ajouter bouton de régénération des factures depuis compte administrateur d'un stolon
+ rustine => en cas de pb de génération des factures quand on clique sur aperçu ou télécharger, la régénération des factures se fait automatiquement.

**Comment by ChavFDG** [comment]
StolonBill
- Ajout de GenerationError
- Mettre la valeur "false" à GenerationError

UPDATE public."StolonsBills"
    SET "GenerationError"=false
