### ISSUE TITLE
Ajouter des explications sur les "Stols" quand on passe la souris dessus

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#25]
Ajouter des explications sur les "Stols" quand on passe la souris dessus.
Il faut prévoir un texte d'explication qu'on ajoutera après.

**Comment by JeanneVoiry** [comment]
Voici une propositin de texte d'explication : 
"Votre portemonnaie virtuel de Stols vous permet de créditer par avance votre compte en euros auprès de votre Stolon. Vous avez ensuite la possibilité de régler vos factures en ligne en utilisant vos Stols."
