### ISSUE TITLE
Supprimer un producteur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#258]
Lorsqu'un compte producteur est supprimé, le producteur continue à apparaître dans "nos producteurs" et on n'a plus la main (En revanche si on passe un producteur en consommateur, il disparaît bien de la liste "nos producteurs").

On a actuellement pas mal de producteurs "fantômes" qui se baladent sur les sites stolons et qu'il faudrait pouvoir supprimer car ça pose des problèmes de visibilité et de compréhension. 
Exemple:
Au stolon du Vernas: 
- GAEC Biquette de la Jaubernie (ATTENTION il y a deux comptes car créé , c'est celui qui n'a pas d'Avatar qui a été supprimé mais qui reste visible) 
- Martin Texier
Au stolon d'Aubenas: 
- La ferme de Saintbiozz
- Muzzolini Ioanina

La question par la suite est aussi de savoir s'il faudra systématiquement passer un producteur qui quitte le stolon en tant que consommateur plutôt que de le supprimer, ou si la résolution de ce bug permettra de supprimer directement un compte producteur?

**Comment by ChavFDG** [comment]
Bug corriger ici #250 .
Pour les comptes fantômes , ils ont était supprimer aussi.

A la prochaine mise à jour la suppression d'un producteur ne posera plus le problème.
