### ISSUE TITLE
IMPORTANT : Problème avec la librairie DinkToPDF

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#27]
J'ai constaté des problème avec la librairie DinkToPDF. 
Quand j'essaie de générer les factures le thread s'arrête un certain temps après la génération de la première factures. Le deuxième appelle à la DLL ne fonctionne jamais. L'envoie des mails plantes par conséquent ou n'est pas effectué vu que le thread a planté.
Je suis entrain de faire des essaies mais pour l'instant sans succès.

Une possibilité serait de changer de librairie. SyncFusion propose des outils gratuitement aux associations et petite entreprise. J'ai déjà utilisé leurs frameworks et je dois dire que c'est de très bonne facture.
Dans leurs prochaine realease il y aura la conversion de HTML en PDF en natif dans le farmework core :
https://www.syncfusion.com/forums/127732/html-to-pdf-converter-asp-net-core
La prochaine version doit être realease ce mois si. Peut être que ça vaut le coup d'attendre ?

**Comment by JeanneVoiry** [comment]
Si on choisit Synfusion, est-ce qu'on serait prêt à éditer des factures le 6 décembre ?

**Comment by ChavFDG** [comment]
Ils ont annoncé la nouvelle version en novembre de cette année. Si ils la sortent bien en novembre on sera en mesure d'éditer les factures.
A savoir qu'on édite déjà les factures au format HTML. Il nous manque juste la conversion en PDF.

**Comment by ChavFDG** [comment]
Bon ben on est niqué :

> Due to stability reason we have not included this feature “Need to add support for HTML to PDF conversion in .net core” in the release (Volume 4, 2017). Currently we are working on this feature with high priority and we will include this feature in our upcoming release Volume 1, 2018 release.

On va devoir trouver une autre solution

**Comment by ChavFDG** [comment]
Je vais regarder pour remettre en place l'utilisation de PhatomJS mais en lui demandant de lire un fichier html plutôt que d'aller sur la page.
https://coderwall.com/p/5vmo1g/use-phantomjs-to-create-pdfs-from-html

**Comment by dyslesiq** [comment]
Apparemment c'est possible (https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js)
simplement en remplacant URL par un chemin de fichier (temporaire par exemple).
Mais je ne sais pas si les css seront bien gérés en chargeant juste un fichier html.

**Comment by ChavFDG** [comment]
Ouip c'est ce que je pense aussi. Je pense que oui car pour le CSS c'est juste un lien vers bootstrap donc le navigateur aura juste à aller chercher le css sur internet du site de bootstrap.
Bref je fais les essaie ce soir ;)

**Comment by ChavFDG** [comment]
On a remplacé PhantomJS par Chronium car PhantomJS généré des PDF vide sous windows.
Il faut donc impérativement avoir chrome ou chronium d'installer sur le serveur ou PC de test. Il est posible de configurer le chemin vers Chrome dans les options du site web.

**Comment by JeanneVoiry** [comment]
bonjour, 
quand je clique sur une facture, j'ai toujours le message "error 404" qui apparaît
qu'en est-il ?

**Comment by ChavFDG** [comment]
Il faut regénérer les factures. Pour cela il faut faire à nouveau un cycle de commande. 
Les factures de la semaine dernière de seront pas dispo mais celle de cette semaine le seront bien.

**Comment by ChavFDG** [comment]
Les factures fonctionnent maintenant bien avec chronium il faut jsute bien configurer chronium
