### ISSUE TITLE
changer de Stolons sur la page d'accueil

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#29]
Quand je me connecte sur Stolons, j'atterris automatiquement sur la page du Stolons de Privas, même si je suis administratrice du Stolon d'Aubenas.
=> pourrait-on faire un page neutre (sans référence à un Stolon en particulier) jusqu'à ce qu'on choisisse le Stolon qu'on veut  pour toutes les personnes qui sont adhérents de plusieurs stolons à la fois ?

De plus quand je veux ajouter de nouveaux adhérents sur le Stolon d'Aubenas "administration/les stolons/stolon d'Aubenas", je me trouve toujours sur la page du Stolon de Privas (voir capture d'écran si dessous) et à chaque ajout de nouveaux adhérents, le site me renvoie à la page des adhérents du Stolon de Privas !

![image](https://user-images.githubusercontent.com/32641097/32736467-d4e593e0-c897-11e7-8ea4-743098da3234.png)

**Comment by ChavFDG** [comment]
A chaque fois que tu te connectes ça te connecte sur le dernier stolon sur le quelle tu étais connecté.

**Comment by JeanneVoiry** [comment]
ah bon ?
à chaque fois que je me connecte sur beta.stolons.org ça me renvoie sur Stolon de Privas automatiquement, et dès que je vais sur Stolon d'Aubenas et que je fais une modification, je suis renvoyée à la page de Stolon de Privas (quand bien même la modification a été réalisée)

**Comment by ChavFDG** [comment]
Ha peut être un bug.
Quelle genre de modification que je reproduise le problème ?

**Comment by JeanneVoiry** [comment]
quand je change le nom d'un producteur par exemple

**Comment by ChavFDG** [comment]
Ca ne le fait pas de mon coté.
Je pense que tu ne t'es pas connecté au Stolon d'Aubenas.
Sur la page tout en haut à droite clique sur la petite flèche sous "Stolon de Privas" puis sur "Stolon d'Aubenas".
![image](https://user-images.githubusercontent.com/16624098/32825195-5264299c-c9e4-11e7-9bad-9d4760e59e87.png)

(oui on a un petit bug d'affichage )

**Comment by JeanneVoiry** [comment]
aaah allright
merci

**Comment by ChavFDG** [comment]
Il faut qu'on change le design de ce changent de Stolon.
Je ferme cet issues et en créer une nouvelle spécifique pour ça.
