### ISSUE TITLE
Ajout catégorie de produit viande

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#3]
Dans la page "mes produits et mes stocks", "ajouter un produit", ajouter la sous-catégorie "viande" dans la catégorie "produits frais".

![image](https://user-images.githubusercontent.com/32641097/31934945-cde7db38-b8ad-11e7-97a0-e661ab369561.png)

**Comment by ChavFDG** [comment]
C'est fait, par contre nous n'avons pas d'illustration pour l'image voir #14
