### ISSUE TITLE
impossible d'ajouter des stocks - stock hebdomadaire

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#31]
Sur le stolon d'Aubenas, en tant que producteur, j'ai ajouté mon produit "botte de radis",
le problème c'est que je n'arrive pas à modifier mes stocks ensuite : quand je clique sur "stock de la semaine : 0 pièces", il n'y a rien qui s'affiche !

![image](https://user-images.githubusercontent.com/32641097/32830531-c94c364c-c9f5-11e7-8094-b38d9af2a2c0.png)

**Comment by JeanneVoiry** [comment]
auriez-vous une réponse pour ce bug ? je pense que c'est un des plus urgents actuellement car les producteurs commencent à entrer leurs produits ! merciii

**Comment by ChavFDG** [comment]
Théoriquement ça a été corrigé par Nico mais je pense que ça n'a pas était mis en ligne encore. Je textote Nico

**Comment by dyslesiq** [comment]
Oui je l'ai corrigé hier soir, je déploie de suite!
