### ISSUE TITLE
URGENT - impossible d'ajouter un produit

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#32]
Un des producteurs d'Aubenas vient de m'appeler et il n'a pas réussi à mettre en ligne ses produits : 
- sur la page d'édition du produit il remplit toutes les infos sur sont produit (en l'occurrence des amandes vendues au kg)
- quand il clique sur "ajouter" rien ne se passe et il reste sur la même page, aucun message d'erreur ne s'affiche
=> le produit n'apparaît donc pas dans la liste des produits..

Ce bug m'est déjà arrivé à plusieurs reprises quand je jouais le rôle de producteur
auriez-vous des pistes ?
merci d'avance

**Comment by ChavFDG** [comment]
On a eu un bug sur les images qu'on a pas encore résolue il me semble.
Qu'il essaie sans son image.

**Comment by JeanneVoiry** [comment]
J'ai résolu en live avec un producteur :
- c'est par rapport aux décimales, il faut mettre une virgule et pas un point pour pouvoir ajouter un produit s
=> pouvez-vous faire apparaître un message d'erreur quand le producteur entre un nombre à décimale en utilisant un point ?

**Comment by ChavFDG** [comment]
Exact, on va faire ça !
Je le donne à Arnaud car ça fait partie d'une modif qu'il avait fait :)

**Comment by JeanneVoiry** [comment]
Nouveau bug soumis par un producteur concernant l'édition d'un produit : 
dans la case "prix au kg" : on ne peut pas entrer de nombre décimal avec une virgule, elle se transforme automatiquement en point et on ne peut donc pas éditer le produit

**Comment by ChavFDG** [comment]
Testé et c'est bien ça. Ca se transforme automatiquement en point ce qui bloque le truc.
Si Arnaud ou Nico peuvent regarder.

**Comment by dyslesiq** [comment]
J'ai fait le changement: maintenant c'est l'inverse, si on entre un '.' à la place d'une ',', il est automatiquement changé.
