### ISSUE TITLE
pb orientation photo des produits

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#33]
une productrice me rapporte que lorsqu'elle met en ligne un photo orienté portrait, la photo apparaît en orientation paysage

**Comment by JeanneVoiry** [comment]
VOici les photos que la productrice de volaille et d'oeufs n'arrivent pas à changer de sens : 

![20171130_123650](https://user-images.githubusercontent.com/32641097/33998514-00e673a2-e0e8-11e7-8efb-4e785ec1e30f.jpg)
![20171130_123536](https://user-images.githubusercontent.com/32641097/33998515-01096146-e0e8-11e7-8562-81cedfa56fd6.jpg)
![20171130_123413](https://user-images.githubusercontent.com/32641097/33998516-012a6dfa-e0e8-11e7-9024-6a377c561f06.jpg)
![20171130_123315](https://user-images.githubusercontent.com/32641097/33998517-01521d32-e0e8-11e7-8f24-52bb761fbbe7.jpg)
![20171117_111533](https://user-images.githubusercontent.com/32641097/33998518-0180ea0e-e0e8-11e7-8af5-21a7cf776a4f.jpg)
![20171117_110404](https://user-images.githubusercontent.com/32641097/33998521-01ddf1c2-e0e8-11e7-9fd4-994dc3c93a07.jpg)

**Comment by dyslesiq** [comment]
Le problème vient des photos en elles-même. On le voit même ici sur github, entre la première de la liste et https://user-images.githubusercontent.com/32641097/33998514-00e673a2-e0e8-11e7-8efb-4e785ec1e30f.jpg
Je suis arrivé à garder la bonne orientation en ouvrant l'image sur mon PC, et faire des rotations jusqu'à ce qu'elle soit correcte et ensuite ré-enregistré l'image.
