### ISSUE TITLE
rajouter logo sur page d'accueil du Stolon d'Aubenas

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#34]
Bonjour

on a besoin de faire apparaitre les logos d'AgriBio Ardèche et des financeurs sur la page d'accueil du Stolon d'Aubenas
On peut imaginer qu'on les rajoute sur l'image de Stolon sur la page d'accueil.
Ce serait possible ?

**Comment by dyslesiq** [comment]
Pour simplifier la mise en place, je verrais bien les logos à la place ou à côté de l'avatar (entre le nom du stolons et l'adresse) ou alors dans le pied de page.
Et j'imagine que si c'est dépendant d'un stolon (Aubenas, Privas, ...), on pourrait rajouter une entrée de configuration par stolon pour avoir une personnalisation de la page d'accueil. Sinon l'affichage sera global (donc pas limité au stolon d'Aubebas).

Pour le détail de l'implémentation:
vu que c'est assez difficile de rendre ca configurable (images, html, ...), on pourrait avoir un dossier de templates dont les fichiers (cshtml/html) porteraient le nom d'un stolon. Un template serait chargé automatiquement par la page d'acceuil en fonction du stolon courant.

**Comment by ChavFDG** [comment]
@JeanneVoiry Les financeurs sont les financeurs de l'outil "Stolons" ? Ou du "Stolon d'Aubenas" ?

Dans le cas où ce sont les financeurs de l'outil dans ce cas il faudrait soit :
- mettre en footer ( en bas de toute les pages l'informations apparaient)
- mettre uniquement sur la page d’accueil de "Stolons" quand on est pas connecter

**Comment by JeanneVoiry** [comment]
les financeurs sont pour l'outil Stolons en général
je vais t'envoyer par mail les logos de tous les financeurs

**Comment by ChavFDG** [comment]
Je verrais bien ça en bas de la page d'accueil de Stolons. Étant donné que c'est pour l'outil Stolons. 
Cela donnerai en gros ça :
![sans-titre-1](https://user-images.githubusercontent.com/16624098/33163266-faf41bae-d02d-11e7-8356-9add329d684c.png)

**Comment by ChavFDG** [comment]
[logo financeurs stolons.docx](https://github.com/ChavFDG/Stolons/files/1502936/logo.financeurs.stolons.docx)

**Comment by ChavFDG** [comment]
Ajouter au dessus des logos cette phrases :

> Le site originel stolons.org (lien projet github), open source, a été créé par quatres bénévoles en 2016 : Damien, Nico, Come et Arnaud avec l'apuie de producteur et consomateur du bassin Privadois (07).
> Les financeurs si dessous on contribué à l'évolution et la multiplication d'utilisateur de la plateforme en 2017.
> [bandeau des financeurs]

**Comment by ChavFDG** [comment]
Serait il possible d'avoir les logos en haute définitions et dans un autre format qu'un fichier word ?

**Comment by JeanneVoiry** [comment]
OK super mais vous pouvez mettre ce petit texte à la place =>
Le site originel stolons.org (projet github), open source, a été créé par quatres bénévoles informaticiens en 2016 avec l'appui de producteurs et consomateurs du bassin Privadois (07).
L'association Agri Bio Ardèche, soutenu par ses partenaires financiers (présentés ci-dessus) a contribué au développement et à la diffusion de la plateforme Stolon à d'autres utilisateurs en 2017.
