### ISSUE TITLE
impossible de changer le stock de produits pendant phase de commandes

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#35]
dans la phase de commande du Stolon d'Aubenas, 
en tant que producteur, quand je cherche à modifier mon "stock restant" pour l'augmenter, quand je clique sur "stock restant" pour mes produits enregistrés en stock hebdomadaire, rien ne s'affiche, est-ce normal ?
ne peut-on pas normalement modifier les quantités (en les augmentant seulement) pendant la phase de commande ?

**Comment by dyslesiq** [comment]
C'est une erreur côté serveur.
Voila l'exception:
Nov 20 12:13:03 stolons-demo xvfb-run[8205]: Newtonsoft.Json.JsonSerializationException: Error getting value from 'ProductId' on 'Stolons.Models.BillEntry'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Stolons.Models.BillEntry.get_ProductId() in /srv/stolons/Stolons/Models/BillEntry.cs:line 52
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at lambda_method(Closure , Object )
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    --- End of inner exception stack trace ---
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
Nov 20 12:13:03 stolons-demo xvfb-run[8205]:    at Stolons.Controllers.ProductsManagementController.JsonProducerProducts() in /srv/stolons/Stolons/Controllers/ProductsManagementController.cs:line 79

**Comment by ChavFDG** [comment]
Nico pourrais tu me dire quelle appel tu fais quand on click sur "stock restant" stp.

**Comment by dyslesiq** [comment]
Je crois que c'est corrigé aussi. Ca marche pour moi, maintenant la page est complètement fonctionnelle.

**Comment by JeanneVoiry** [comment]
ça fonctionne!
