### ISSUE TITLE
Error 404 pour "j'ai oublié mon mot de passe"

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#36]
https://beta.stolons.org/Home/ForgotPassword
=> sur la page d'accueil de Stolon, quand on clique sur "j'ai oublié mon mot de passe", le message "error 404" apparaît.

**Comment by ChavFDG** [comment]
Le lien vers la page de récupération du mot de passe était erroné . Problème résolue. Il faut tester la récupération maintenant.

**Comment by JeanneVoiry** [comment]
j'ai toujours le message "Error 404" qui apparaît quand je clique sur "j'ai oublié mon mot de passe"

**Comment by ChavFDG** [comment]
La correction a été effectué il y a deux jours mais vient juste d'être mis à jour sur le serveur. Tu peux à nouveaux tester.

**Comment by JeanneVoiry** [comment]
je viens de tester

en cliquant sur "j'ai oublié mon mot de passe" je tombe effectivement sur la bonne page où il faut renseigner son adresse email, par contre quand j'ai validé une première fois je suis tombée sur "504 bad gateway", en réessayant ça a marché et j'ai reçu un mail avec un lien pour accéder au nouveau mot de passe.
par contre, en cliquant sur ce lien j'atterris sur la page suivante : 

![image](https://user-images.githubusercontent.com/32641097/33173547-daaae3f6-d054-11e7-88de-889fabea3178.png)

**Comment by JeanneVoiry** [comment]
ça ne marche toujours pas !

**Comment by ChavFDG** [comment]
C'est bon ça devrait marcher. L'url générré pour le changement du mot de passe ne tenait pas en compte de l'url du site internet.
En debug ça renvoii sur localhost:5000.
En release ça renvoyé sur "www.stolons.org" maintenant ça renvera sur ce qui a été configurer dans le site.
