### ISSUE TITLE
impossible de valider mon panier

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#37]
en tant que consommatrice sur le Stolon d'Aubenas, je n'arrive pas à valider mon panier car l'onglet "valider mon panier" n'apparaît pas en bas de la page, voir capture d'écran ci jointe : 

![image](https://user-images.githubusercontent.com/32641097/33019680-a9b07032-cdfb-11e7-87b4-701b43f8c9e7.png)

**Comment by JeanneVoiry** [comment]
je pense qu'il est impossible de valider le panier quand on a dans son panier un produit qui n'est plus disponible car déjà commandé par un autre consommateur

**Comment by dyslesiq** [comment]
Oui ce comportement est voulu et on ne pourra pas faire autrement.
C'est un système "premier arrivé, premier servi".
C'est la validation d'un panier qui réserve les produits et c'est seulement à ce moment la que les stocks sont vérifiés/mis à jours.
Nous gérons déjà la validation partielle d'un panier: le cas ou la totalité des produits commandés ne seraient plus disponibles.

**Comment by dyslesiq** [comment]
Pour le problème d'affichage: ajouter un scroll vertical dans la liste des produits commandés sur la droite ?

**Comment by JeanneVoiry** [comment]
Pour clarifier le système "premier arrivé, permier servi" dans le cas où deux consommateurs A et B commandent au même moment le même produit qui est en quantité limité : 
imaginons que A et B commandent ensemble du sirop de sureau présent en 5 exemplaires. A et B en commandent chacun 5. A valide son panier en premier. Quand B veut valider son panier, le bouton "valider votre panier n'apparaît pas" (c'est ce qu'il m'est arrivé quand on a fait le test avec Benoît..) => pourrait-on faire apparaître un message d'erreur qui signifie au consommateur B qu'il ne peut pas valider son panier car il contient des produits qui ne sont désormais plus disponibles + pourrait-on faire disparaître automatiquemen du panier ce produit qui n'est plus disponible ?

**Comment by dyslesiq** [comment]
Normalement quand B veut valider son panier, il devrait pouvoir le faire.
C'était le cas avant en tout cas!
Il aura alors un avertissement comme quoi son panier a bien été validé, mais seulement partiellement car le sirop n'était plus disponible dans la quantité demandée.

**Comment by ChavFDG** [comment]
@JeanneVoiry  Je confirme bien le dernier message de @dyslesiq  :
- **A** met dans son panier 5 sirops, il valide et arrive sur la page de validation de son panier
- **B** met ans son panier 5 sirops, il valide et arrive sur la page de validation **partiel** de son panier

La page de validation partiel affiche la liste des produits validé et la liste des produits non validé ( car entre temps quelqu'un d'autre a validé son panier avant).

@JeanneVoiry Concernant ton bug de bouton "Valider le panier" qui n'apparait pas. Cela n'a rien à voir avec la non disponibilité d'un produit. C'est un "bug visuel" le panier s'étend tant que tu rajoutes des produits mais la page ne s'agrandit pas et aucun ascenseur apparait.
En fait ton bouton se trouve ici :
![image](https://user-images.githubusercontent.com/16624098/33063710-8c108e2e-cea3-11e7-9b75-7a0387a6b8e6.png)


Bug a réglé, très urgent. Envoyé à Come ;)

**Comment by JeanneVoiry** [comment]
en effet bug urgent,
tenez moi au courant de où  vous en êtes
on pourra retester la semaine prochaine quand on sera à nouveau en période de commandes
