### ISSUE TITLE
Envoi d'un mail de confirmation lorsque changement de mot de passe

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#38]
il serait utile que les adhérents reçoivent un mail de confirmation de changement de leur mot de passe

**Comment by ChavFDG** [comment]
Ajout de l'envoie d'un mail de confirmation de changement de mot de passe. Fonction à tester.

**Comment by JeanneVoiry** [comment]
je viens de tester, je n'ai pas reçu d'email de confirmation de changement du mot de passe

**Comment by ChavFDG** [comment]
La correction a été effectué il y a deux jours mais vient juste d'être mis à jour sur le serveur. Tu peux à nouveaux tester.

**Comment by JeanneVoiry** [comment]
OK ça fonctionne, parfait !
