### ISSUE TITLE
affichage des produits sur la page de présentation du Stolon d'Aubenas

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#39]
Sur la page de présentation du Stolon d'Aubenas, il y a une rubrique "produits" où sont affichés uniquement les produits de la boulangerie qui ne sont pas les produits qu'on retrouve dans la liste des produits disponibles ! (voir capture d'écran), 

=> à mon avis cette rubrique n'est pas pertinente ou alors il faudrait seulement indiquer la liste des produits disponibles sur le drive par famille (légumes/fruits/oeufs/produits laitiers/viande/produits d'épicerie/boissons)

![image](https://user-images.githubusercontent.com/32641097/33020453-aab4eb4a-cdfe-11e7-88e1-5e221b407a01.png)

**Comment by ChavFDG** [comment]
Cette page à deux fonctions :
- Quand on est connecté, voir les informations de contact de son stolon 
- Quand on est pas connecté avoir une présentation du stolon.

Si tu te déconnectes tu peux aller voir ici :
https://beta.stolons.org/Home/StolonContact/ac42c9e5-2118-4402-b60c-b64451ea0df0

**Comment by JeanneVoiry** [comment]
bonjour, 

je réitère ma remarque formulée précédemment : 
=> à mon avis cette rubrique n'est pas pertinente ou alors il faudrait seulement indiquer la liste des produits disponibles sur le drive par famille (légumes/fruits/oeufs/produits laitiers/viande/produits d'épicerie/boissons)

+ il y a une faute de frappe : "horaires" et non pas "horarires"

**Comment by dyslesiq** [comment]
Discuté briévement aved Damien: ce n'est pas une priorité fonctionnelle et il faudrait réflechir un peu plus à l'affichage 'non connecté', c'est à dire affichage des producteurs et des produits par Stolons, sous une forme de vitrine.
Et en effet l'affichage des produits sur cette page n'est pas pertinent car c'est une liste 'en dur', qui ne reflète pas les vrais produits.
Au niveau de l'implémentation, il serait aussi possible de factoriser l'affichage des produits de cette page avec la possibilité pour les producteurs de voir le rendu de leurs produits après édition.

**Comment by ChavFDG** [comment]
Voir point #56
