### ISSUE TITLE
Lisibilité des quantités disponibles par producteur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#4]
Sur la page "gestion de mes produits et de mes stocks", 
je trouve plus pertinent de rendre compte du stock disponible des produits en utilisant les unités L et KG plutôt que mL et g. 
par ailleurs, pourquoi y a-t-il un tiret devant le nombre indiqué en ce qui concerne "le stock de la semaine" ? si le tiret n'est pas utile, je pense qu'il vaut mieux l'enlever, d'autant plus qu'il fait référence à une quantité négative. 

![image](https://user-images.githubusercontent.com/32641097/31935994-90fef0e6-b8b0-11e7-90de-472b8c69fedb.png)

**Comment by ChavFDG** [comment]
Le tiret ainsi que l'affichage des g et ml était du à un autre bug corrigé (#9)

Concernant l'affichage du poids, ce dernier est intelligent. Quand la valeur du stock est supérieure à 1000gr l'affichage est effectué en kg et quand elle est inférieure à 1000gr l'affichage est en gr, prareil pour les litres et ml.
