### ISSUE TITLE
affichage onglet compte consommateur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#40]
Quand je suis un simple consommateur, il n'y a que l'onglet "mon panier" qui apparaît sur mon compte.
Il serait judicieux d'inclure également l'onglet "nos producteurs" qui renverrait à une page qui liste les producteurs (comme sur la page du stolons.org seulement quand on n'est pas connecté) + inclure l'onglet "mes nouvelles".

![image](https://user-images.githubusercontent.com/32641097/33020730-999ddd66-cdff-11e7-84b4-d430abfd1807.png)

**Comment by ChavFDG** [comment]
@JeanneVoiry il n'y a pas d'onglet "**mes** nouvelles" car un simple utilisateurs ne peut pas ajouter de nouvelle.
Pour "Nos producteurs" il faut clicker sur "Stolon d'Aubenas" en haut à droite pour avoir la page qui affiche la carte des producteurs.

On pourrait en effet ajouter l'onglet "Les nouvelles" sachant qu'en cliquant sur "Stolons" on arrive sur les nouvelles. Et que ce serait étrange d'avoir ces onglets et ne pus les avoir une fois qu'on serait bénévole ou autre ?

**Comment by JeanneVoiry** [comment]
ok merci pour ton retour
je trouve cependant que ce n'est pas très intuitif de devoir cliquer sur "stolon d'Aubenas" pour avoir la liste des producteurs (qui est seulement une carte qui plus est..) je pense qu'avoir une présentation comme pour le Stolon de Privas avec un onglet "nos producteurs" serait chouette mais ça n'est pas urgent pour le lancement de la nouvelle version

**Comment by ChavFDG** [comment]
Exact je le laisse de coté, on regardera pour ajouter cela dans une prochaine version

**Comment by ChavFDG** [comment]
C'est fait. On a ajouter un bouton Accueil ainsi que "nos producteurs"
