### ISSUE TITLE
URGENT - commandes de cette semaine pas prise en compte

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#41]
sur mon compte client j'ai commandé des produits cette semaine pour un montant total de 34 € pour lequel j'ai reçu un mail de confirmation. 
Or, la phase de commande a pris fin hier à midi et lorsque je vais sur mon compte dans "mes commandes", il apparaît une commande d'un montant de 0 €... ma commande n'a donc pas été prise en compte ?

**Comment by ChavFDG** [comment]
Au niveau de tes commandes la commande est bien de 34€ :
![image](https://user-images.githubusercontent.com/16624098/33148309-a459c724-cfcb-11e7-9a26-254a0fba8e4b.png)

Peux tu me faire une capture de où tu vois une commandes à 0€ s'il te plait ?

**Comment by ChavFDG** [comment]
Si tu cliques sur la zone en bleu :
![image](https://user-images.githubusercontent.com/16624098/33172208-7278744c-d04f-11e7-9386-71fd8bf2613d.png)
Le détail apparait à gauche.

Si tu cliques sur télécharger, ça lance le téléchargement de la facture en pdf. Sauf pour le moment car la fonction de génération de la facture en pdf merdouille. On fait une réunion de dev ce soir sur tout les points urgents dont celui ci.

**Comment by JeanneVoiry** [comment]
top !
OK je vais avancer sur les bugs/améliorations du site aujourd'hui de mon côté
