### ISSUE TITLE
Impossible de rectifier la livraison

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#42]
En tant qu'administrateur, quand je suis dans "gérer les paniers",  et que je cherche à rectifier la livraison d'un producteur (au passage, on écrit rectification sans accent), je ne peux pas valider => le bouton "valider" est grisé

![image](https://user-images.githubusercontent.com/32641097/33128098-7d12e73a-cf8b-11e7-8aca-ce568409a1e3.png)

**Comment by ChavFDG** [comment]
C'est normal la fonctionnalité n'est pas encore finis. On travail justement ce soir dessus.
