### ISSUE TITLE
Mauvais nom du site dans le mail de création du compte stolon

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#43]
dans le mail de création du compte stolons, 
c'est la page www.stolons.org qui est renseignée et non pas beta.stolons.org
=> est-ce qu'une fonctionnalité est prévue pour bien renseigner la bonne adresse du site sur lequel a été créé le compte dans le mail de création du compte ?

merci !

**Comment by ChavFDG** [comment]
Le mail de création de compte est écrit en dur. Le jours ou on basculera tout le monde sur www.stolons.org ou on changera de nom on fera ce changement.
