### ISSUE TITLE
mention "NaN" dans case prix unitaire

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#44]
quand on entre un produit avec un prix au kg, pourquoi menion "NaN" dans la case "prix unitaire" ? pourquoi ne pas seulement griser la case (d'ailleurs c'est bien si elle est plus grisée car sur mon écran on ne voit pas bien la différence)

![image](https://user-images.githubusercontent.com/32641097/33176265-c96eb798-d05e-11e7-99d6-172cc6722afa.png)

**Comment by ChavFDG** [comment]
C'était un bug, réglé dans le cas  #45
