### ISSUE TITLE
URGENT - impossible d'ajouter un produit

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#45]
je rentre les infos suivantes pour ajouter un nouveau produit : 
![image](https://user-images.githubusercontent.com/32641097/33176475-74587b94-d05f-11e7-8e66-0a2ca0f0ed44.png)

je fais ajouter et je reste sur la même page..

que se passe-t-il ?
d'autres producteurs ont ce même problème et n'arrive pas à ajouter ou éditer leurs produits

**Comment by ChavFDG** [comment]
Ok j'ai trouvé le bug et je l'ai corrigé, je vais voir pour une mise à jour du site.
Ca vient du "NaN" qui est affiché qui n'est pas une valeur valide et donc qui empêche la sauvegarde.
