### ISSUE TITLE
URGENT - Comment télécharger toutes les factures consommateurs pour les imprimer d'un coup et les placer dans les cagettes ?

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#46]
dans la v1 de Stolons, il est possible de télécharger d'un coup toutes les factures consommateurs, voir ci-dessous : 
![image](https://user-images.githubusercontent.com/32641097/33180837-62a69e94-d06e-11e7-8d4d-def33ca1fb99.png)
 
Est-ce qu'on aura accès à cette option dans la V2 ?

**Comment by ChavFDG** [comment]
Très bonne question, on aura en effet cette possibilité de télécharger ( uniquement en mode livraison/stock ) :
![image](https://user-images.githubusercontent.com/16624098/33181132-623297fa-d06f-11e7-8971-ab86f39469a8.png)
Ainsi que la possibilité de voir en direct sur le site ( nouvelle fonctions)
