### ISSUE TITLE
Impossible de valider le paiement

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#47]
En tant qu'administratrice du Stolon d'Aubenas, quand je vais dans l'onglet "gérer les paniers" et que je clique sur "valider le paiement de la facture", un message d'erreur apparaît (voir capture d'écran ci-dessous)

![image](https://user-images.githubusercontent.com/32641097/33180914-a304c8bc-d06e-11e7-87d2-fdeff51c6145.png)

**Comment by dyslesiq** [comment]
C'est corrigé!
