### ISSUE TITLE
Explication DLC

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#5]
Sur un compte de producteur, dans la rubrique "mes produits et mes stocks", "ajouter un produit",
je pense qu'il est nécessaire de documenter la manière de remplir le champ de la DLC "0001-01-01T00:00:00.000" qui n'est pas intuitive

=> peut-être mettre une explication avec un point d'interrogation à côté de "DLC" ?

![image](https://user-images.githubusercontent.com/32641097/32222233-bf336bda-be38-11e7-89a4-3a6de305d464.png)

**Comment by ChavFDG** [comment]
Serait il possible d'avoir des explications sur la DLC des produits vendu en ligne ainsi que les produits frais ?
Car quand est il d'une DLC de carotte ?
Ne faut il pas juste ajouter à consommer dans les N jours ?
Quand est il de la législation ?

**Comment by dyslesiq** [comment]
Je n'ai rien trouvé de particulier pour la vente en ligne mais voici les régulations pour les produits frais: https://www.service-public.fr/particuliers/vosdroits/F10990
Il me semble que tant que la date est indiquée sur le produit (ce qui n'est pas la résponsabilité du site), c'est bon.

Par contre si on veut faire apparaître les même dates sur le site, alors il faut revoir la facon dont on le gère car la DLC peut dépendre de la date d'achat.
Exemple ici: https://www.vracnroll.com/les-douceurs-de-delibio-brownie-noisettes-p308

**Comment by JeanneVoiry** [comment]
salut,
Pour tout ce qui est contenu (DLC, explication Stols, etc) je vois avec Benoît et je reviens vers vous, ne vous en occupez pas pour l'instant!

**Comment by JeanneVoiry** [comment]
Le plus simple est de supprimer le champ "DLC" dans l'édition d'un produit pour simplifier la tache des agriculteurs qui la mettront plutôt dans le descriptif écrit du produit. Par exemple pour les oeufs, ils pourront écrire "à consommer dans les 3 semaines" et non pas écrire une date précise (qui elle sera inscrite physiquement sur le produit).

**Comment by ChavFDG** [comment]
Ok, ne faudrait il pas rajouter une petite explication (comme pour les stols) au niveau de l'édition d'un produit sur le champ "description".
Afin de lui dire de bien expliquer/préciser le type de produit et d'entre la DLC quand cela est nécessaire ?

**Comment by JeanneVoiry** [comment]
oui on peut le faire :
indiquer la description du produit et la mention "à consommer sous ...
jours" pour les produits concernés
