### ISSUE TITLE
Ajouter une distinction en fonction du type de producteur

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#51]
Ajouter une distinction en fonction du type de producteur. Il y aura trois types de producteurs :
- Producteur
- Transformateur
- Distributeur
Chacun ayant des restrictions sur les produits qu'il peut proposer en fonction de la charte global et local.

Cette distinction doit être ajouter dans la configuration du producteur ainsi que visuellement sur la vente des produits, de cette manière :
![avant apres](https://user-images.githubusercontent.com/16624098/33239657-c62f1e0c-d2a6-11e7-9f27-2f5ebee9d033.jpg)

**Comment by ChavFDG** [comment]
Il faudra le faire aussi apparaitre ici, de manière à distinguer en un coup d'yeux les différents type de producteurs  : 
![image](https://user-images.githubusercontent.com/16624098/33242144-7ce0aa48-d2d0-11e7-8322-636e19e2031a.png)

**Comment by JeanneVoiry** [comment]
oui il faudrait l'ajouter ici pour bien faire la distinction

![image](https://user-images.githubusercontent.com/32641097/33257709-722609d6-d357-11e7-9b61-0ac84c25f75e.png)

super idée en tout cas !

**Comment by ChavFDG** [comment]
C'est déjà fait : 
![image](https://user-images.githubusercontent.com/16624098/33266443-fd79374c-d375-11e7-8d65-d43a24dc5c28.png)
