### ISSUE TITLE
incohérence dans le  niveau des stocks

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#53]
En tant que producteur, 
quand j'ajoute le produit "riz demi complet de Camargue", quand je le rends disponible, 
dans il en reste en stock je renseigne "500 KG", j'enregistre les modifications mais il est inscrit seulement "50 kg" dans le stock restant de ce produit (voir capture d'écran ci-dessous) : 

![image](https://user-images.githubusercontent.com/32641097/33257995-75910638-d358-11e7-95aa-873ae743a6b8.png)

**Comment by JeanneVoiry** [comment]
OK je viens de comprendre la logique, 
ce qu'"il reste en stock" est le nombre de quantité de palier de vente et non pas le nombre de KG total

=> ce n'est pas intuitif !
a mon avis il faut que ce qu'"il reste en stock" soit équivalent au poids restant en kg !!

**Comment by dyslesiq** [comment]
C'est corrigé et mis à jour sur le serveur.
