### ISSUE TITLE
impossible de modifier le stock restant en période de commande

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#55]
quand je suis en période de commande et qu'en tant que productrice j'ajoute un nouveau produit, je suis incapable de modifier le stock restant ! quand je clique sur "stock restant" rien ne se passe.

**Comment by dyslesiq** [comment]
Je n'arrive pas à reproduire le bug. Est-ce que tu pourrais ré-essayer en notant tous les paramètres du produit stp ?

**Comment by JeanneVoiry** [comment]
c'est normal parce qu'on n'est pas en période de commande actuellement mais en période de mise en stock

veux tu que je change les paramètres du stolon ? (se placer en mode simulation ?)

**Comment by dyslesiq** [comment]
Je l'ai déjà testé en mode simulation

**Comment by JeanneVoiry** [comment]
c'est bon ça fonctionne merci
