### ISSUE TITLE
erreur orthographe

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#6]
dans un compte de producteur, onglet "mes stocks et mes produits", "ajouter un produit", 
ton écrit "réfrigérateur" et non pas "réfrégirateur"

![image](https://user-images.githubusercontent.com/32641097/32222285-f6267344-be38-11e7-87ec-da95182a16e2.png)

**Comment by ChavFDG** [comment]
Corrigé !
