### ISSUE TITLE
En période commande quand on modifie le stock on a plus le stock initial

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#60]
En période commande quand on modifie le stock on a plus le stock initial ni l'information sur la quantité prise par les adhérents :
![image](https://user-images.githubusercontent.com/16624098/33422001-5efc96a4-d5b4-11e7-83e5-feaeece26b35.png)

**Comment by ChavFDG** [comment]
De plus il faut cliquer deux fois sur "Enregistrer les modifications"

**Comment by dyslesiq** [comment]
Pour les produits en type de stock à la semaine on affiche maintenant la quantité commandée cette semaine et on met à jour le stock de la semaine en même temps que le stock restant.
