### ISSUE TITLE
URGENT poids au KG différent poids par palier 

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#63]
Le poids au KG n'est pas le même que le poids pour 500 g pour le "paquet de 2 cuisses de poulet sous vide" et les autres produits !!!
=>

![image](https://user-images.githubusercontent.com/32641097/33423640-b4be8bce-d5b9-11e7-97a8-65bc23871b3b.png)

autre problème avec le poids au kilo : 
quand j'ai indiqué un mauvais palier (exemple : palier de 1g), que j'ajoute mon produit puis que je fais modifier mon produit et que j'entre le palier juste => le poids par unité ne se modifie pas !
et quand on supprime le prix et le poids au kg, le poids par unité reste affiché ! voir image ci dessous 

![image](https://user-images.githubusercontent.com/32641097/33429605-d4ec01e2-d5cd-11e7-978f-fa6a6261f4fb.png)

**Comment by JeanneVoiry** [comment]
par contre, je pense qu'on peut se passer de résoudre ce beug pour le lancement, si le producteur vend à la pièce plutôt qu'au poids

**Comment by JeanneVoiry** [comment]
ça ne marche toujours pas

**Comment by ChavFDG** [comment]
J'ai corrigé ce bug, on a pas encore mis a jour sur le serveur.

**Comment by JeanneVoiry** [comment]
ok ça marche superbe!
