### ISSUE TITLE
Carte des stolons sur page d'accuiel

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#64]
en attendant d'avoir la carte avec les producteurs, on pourrait mettre cette photo dans la page d'accueil stolon 

![page d accueil stolon](https://user-images.githubusercontent.com/32641097/33434859-db1c0f54-d5e0-11e7-86be-341a47b38aca.JPG)

**Comment by JeanneVoiry** [comment]
est-ce possible de le faire??

**Comment by ChavFDG** [comment]
On va ajouter la carte des stolons plutôt qu'une image.
