### ISSUE TITLE
SUPER URGENT - le panier ne s'affiche pas en mode commande

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#65]
en mode commande, le panier ne s'affiche pas 

![image](https://user-images.githubusercontent.com/32641097/33435009-569e0cfe-d5e1-11e7-89f5-954cc6e12beb.png)

**Comment by dyslesiq** [comment]
Après un peu d'investigations, c'est l'appel api/Products qui pose problème.
Il consomme toute la mémoire du serveur avant de le faire planter...
Il faut trouver la cause du problème et mettre en place des solutions pour éviter que ca ne se reproduise sur d'autres appels.
Quelques pistes:
- Retravailler les requêtes
- https://docs.microsoft.com/en-us/ef/core/querying/tracking
- Limiter au maximum les références récursives
- Comprendre plus en détails comment entity framework  fonctionne

**Comment by dyslesiq** [comment]
C'est corrigé! Il reste un petit problème de performance (l'affichage sera un peu long, surtout pour ceux qui on une mauvaise connexion).
On va essayer de résoudre ca rapidement.

**Comment by JeanneVoiry** [comment]
ok super le panier s'affiche maintenant
