### ISSUE TITLE
Stock négatif pour un produit

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#66]
le stock de chou-rave est négatif, voir ci dessous 

![image](https://user-images.githubusercontent.com/32641097/33475528-06b9bcd0-d67f-11e7-80c1-3fff5a375593.png)

**Comment by ChavFDG** [comment]
Ce doit être du aux anciens bug qu'on a eu. Il faudrait voir si on peut remettre le stock du produit à 0. Sinon le supprimer et le recréer.
