### ISSUE TITLE
impossible de supprimer des produits => seule option : les archiver

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#68]
un producteur n'a pas réussi à supprimer deux produits qu'il avait mis en ligne au début de la phase test (il y a environ 2 semaines)
du coup il a été obligé d'archiver les produits !

voir photo 
![image](https://user-images.githubusercontent.com/32641097/33476889-e16715d6-d683-11e7-87e0-caed16826b8e.png)

**Comment by ChavFDG** [comment]
On peut uniquement supprimer un produit qui n'a jamais été commandé dans le passé et on peut supprimer un produit uniquement en période de stock.
