### ISSUE TITLE
ajouter choix dans stockage des produits

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#7]
sur le compte d'un producteur, dans la rubrique "mes produits et mes stocks", "ajouter un produit", 
je pense qu'il est nécessaire d'ajouter le choix "stocker dans un congélateur" car certains produits (steacks hachés surgelés notamment) le seront.

![image](https://user-images.githubusercontent.com/32641097/32222344-2f913b6e-be39-11e7-8ee0-7b5e9404f8c7.png)

**Comment by ChavFDG** [comment]
Je propose d'ajouter un choix par liste déroulante :
A stocker dans :
- Panier _(choix par défaut)_
- Réfrigérateur
- Congélateur
Ne faut il pas faire une distinction au niveau du réfrigérateur entre les fromages et la viandes pour se conformer à la réglementation ?

**Comment by JeanneVoiry** [comment]
pas besoin de faire une distinction au niveau du réfrigérateur entre les fromages et les viandes pour se conformer à la réglementation. (on peut mettre fromages et viandes dans le même frigo sans problème).
par contre, quelle utilité de ce champ pour le producteur et/ou le consommateur ? où apparait ensuite cette option de stockage ? dans la facture qui est envoyé au consommateur pour lui rappeler qu'il a acheté des produits frais ?
a mon avis, si l'option de stockage n'apparaît nulle part ailleurs ensuite, il faut la supprimer !

**Comment by ChavFDG** [comment]
Pour faire apparaitre sur les fiches sur le paniers :
![image](https://user-images.githubusercontent.com/16624098/32882843-e8b98aa0-cab5-11e7-89c3-6ccaebb9530d.png)
De manière à éviter les oublies dans les frigos.

**Comment by JeanneVoiry** [comment]
ok
laisse moi voir ce soir ce qu'il en est

**Comment by ChavFDG** [comment]
Ok. En gros je dirais :
- Panier (choix par défaut) (petit logo panier)
- Réfrigérateur (logo flocon 0-5°)
- Congélateur (logo flocon -15°, -18°)

**Comment by ChavFDG** [comment]
Pour être précis sur les fiches qu'on colle sur les paniers.
Fiche différente des factures conso.

**Comment by ChavFDG** [comment]
Les trois catégorie on était ajouté pour la création / édition d'un produit, à savoir :
    Panier (choix par défaut)
    Réfrigérateur 
    Congélateur 

Il faut maintenant l'ajouter dans sur le détail d'un produit ainsi que sur les fiches consomateurs à mettre sur les paniers.
