### ISSUE TITLE
SUPER URGENT Difficulté à ajouter un produit 

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#70]
en mode commande, quand je clique sur un produit pour l'ajouter, ça rame (les deux flèches qui tournent). 
pour que mon produit se retrouve dans mon panier, il faut que je change de page (par exemple, je clique sur "mes produits et mes stocks") puis que je retourne sur la page "mon panier" et là, mon produit est bien dans mon panier...

**Comment by ChavFDG** [comment]
Fait le test de mon coté ça marche bien.

**Comment by JeanneVoiry** [comment]
c bon ça fonctionne merci
