### ISSUE TITLE
impossible de valider son panier une fois qu'on l'a modifié

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#77]
Quand je fais "modifier mon panier" et que j'ajoute de nouveaux produits, il s'affiche bien dans mon panier sur la droite par contre le bouton "valider votre panier" a disparu et ces changements ne sont pas pris en compte!!
c'est urgent car beaucoup de personnes se sont faites avoir..!!
merci

**Comment by dyslesiq** [comment]
C'est corrigé!
