### ISSUE TITLE
Ajouter la marque collective "Goûtez l'Ardèche" => attendre confirmation de mon chef ^^

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#8]
dans le compte des producteurs, rubrique "mes produits et mes stocks", "ajouter un produit"
parmi les choix de labels et certifications, ajouter la marque collective "goûtez l'ardèche" (voir logo ci-joint)

![label goutez l ardeche](https://user-images.githubusercontent.com/32641097/32222425-817934c2-be39-11e7-9225-3458c3ab59b3.png)

**Comment by ChavFDG** [comment]
Ok c'est bon,j'ai aussi ajouté Label Rouge et BioPartenaire.
Les labels disponibles sont :
- AB
![ab](https://user-images.githubusercontent.com/16624098/32699670-d7e89954-c7b9-11e7-8a9a-81c30b55dc22.jpg)
- Demeter
![demeter](https://user-images.githubusercontent.com/16624098/32699672-d834e62e-c7b9-11e7-8802-3a56c86c3342.jpg)
- Goutez l'Ardèche
![goutezardeche](https://user-images.githubusercontent.com/16624098/32699673-d85aede2-c7b9-11e7-8e5a-226003ec4cd4.jpg)
- Max Havelaar
![maxhavelaar](https://user-images.githubusercontent.com/16624098/32699675-d8a42a2a-c7b9-11e7-810f-449101a0a75c.jpg)
- Nature et Progres
![natureetprogres](https://user-images.githubusercontent.com/16624098/32699676-d8c8b53e-c7b9-11e7-871d-30f0df302a26.jpg)
- Label Rouge
![labelrouge](https://user-images.githubusercontent.com/16624098/32699674-d87fc43c-c7b9-11e7-9b68-7447684e2960.png)
- Bio partenaire 
![biopartenaire](https://user-images.githubusercontent.com/16624098/32699671-d8107118-c7b9-11e7-8407-0f783ca0c483.jpg)



Y en a t'il d'autre à ajouter ?
Bio Cohérence ? 
![biocoherence](https://user-images.githubusercontent.com/16624098/32699692-1168208c-c7ba-11e7-9d7d-609e5f03323a.jpg)

Ne faudrait il pas avoir une annotation spéciales pour les producteurs en conversion vers le bio ?
Car si un producteur en conversion coche AB son produit apparait avec le logo AB, hors il me semble qu'en fonction de l'année de conversion il n'a pas le droit de faire apparaitre le logo ou doit avec une dénomination particulière. ?

**Comment by JeanneVoiry** [comment]
En ce qui concerne la liste des logos, on supprime "Max Havelaar" car si on le garde on devrait aussi mettre tous les logos du commerce équitable sur Innovance. 
OK pour rajouter le label Bio Cohérence
Pour ce qui du label AB, il est autorisé pour les produits en dernière année de conversion donc pas besoin de rajouter une annotation.

**Comment by ChavFDG** [comment]
Ok, cela signifie que si on autorise les producteurs en premier année de conversion. Ils ne devrons pas mettre leurs produits en bio sur le site.
Il pourra uniquement le mettre lors de la dernière année de conversion.

**Comment by JeanneVoiry** [comment]
exactement!

2017-11-16 9:06 GMT+01:00 ChavFDG <notifications@github.com>:

**Comment by ChavFDG** [comment]
Concernant les catégories de produits vous nous avez demandé le schéma suivant : 

- Boulangerie : pains, pâtisseries, farines
- Fruits
- légumes
- Produits laitiers
- Oeufs
- Viandes : volaille, boeuf, agneau, conserves
- Conserves végétales : confitures, tartinades, autres
- Boissons : alcool, sans alcool
**- Distributeur : légumineuses, fruits secs, céréales, boissons, fruits, légumes**

Ok pour rajouter. Mais concernant une catégorie "Distributeur" cela me semble pas très logique. On est ici dans un système de catégorisation des produits, non pas des types de fournisseur. Ne faudrait il ta plutôt rajouter un type "Fournisseur" avec une distinction sur le produit plutôt qu'une catégorie ?
Cela va faire doublon car si on un producteur local de poids chiche "catégorie légumineuses" cela créera un doublon de catégorie. Comme le cas des fruits et des légumes.
Si je cherche des "pommes" il faudra que je regarde dans Fruit et dans Distributeur => Fruit ...

**Comment by ChavFDG** [comment]
Après discussion avec Benoit on va partir sur un système de catégorie de producteur.
Voir issue #51 .
