### ISSUE TITLE
Ajout d'un mode de maintenance  dans la configuration du site

### ISSUE THREAD

**Issue by dyslesiq** [ChavFDG/Stolons#80]
J'ai ajouté un mode de maintenance (qui affiche seulement la page https://aubenas.stolons.org/maintenance.html) au niveau du serveur nginx.
Si on veut le déclencher sans avoir à modifier la config serveur, il faut juste créer un fichier '\_maintenance\_' dans le dossier wwwroot.
Cela peut aussi permettre d'interdire l'accès au site rapidement si on repère un bug critique ou pour autres situations.

**Comment by ChavFDG** [comment]
Ca a l'air d'être fait !
