### ISSUE TITLE
Problème sur envoie des mails automatiques

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#82]
depuis quelques semaines, cette fonctionnalité ne marche plus et on doit envoyer un mail nous-mêmes !

**Comment by dyslesiq** [comment]
C'est un petit oubli de notre par lors des développement, l'envoi avait été désactivé! C'est corrigé.

**Comment by JeanneVoiry** [comment]
ok ça fonctionne par contre , peut-on changer le "�" par "à" dans le mail automatique envoyé ?
--> Mot de passe : identique � votre courriel

**Comment by JeanneVoiry** [comment]
le mail automatique d'ouverture des commandes fonctionne bien
