### ISSUE TITLE
Difficulté pour supprimer des produits du panier

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#83]
Lorsqu'on clique sur l'icône de la poubelle rouge pour supprimer un produit, rien ne se passe, il faut actualiser la page pour que le produit disparaisse du panier

**Comment by JeanneVoiry** [comment]
hello !
ce problème est assez urgent, chaque semaine j'ai des retours de consommateurs qui ont des difficultés à ce niveau, pour valider/modifier un panier !

**Comment by nmichon** [comment]
Hello! Il faudrait vérifier lors des prochaines commandes que ce bug existe toujours.

**Comment by dyslesiq** [comment]
Je ferme ce bug, j'ai du le corriger la dernière fois, à ré-ouvrir s'il y a encore des problèmes
