### ISSUE TITLE
Les encarts de présentation des produits ne font pas tous la même taille

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#87]
D'un point de vue esthétique, je trouve qu'il serait mieux d'avoir des encarts de même taille, sinon ça fait des "trous" dans la présentation des produits : 

![image](https://user-images.githubusercontent.com/32641097/35032333-d9e93ebc-fb66-11e7-9ce9-9ad52470d18e.png)

**Comment by dyslesiq** [comment]
C'est corrigé mais pas encore déployé,  a priori on mettra le site à jour en fin de semaine.

**Comment by JeanneVoiry** [comment]
en local sur Stolon test https://beta.stolons.org/WeekBasket

toujours le même problème de différence de taille des encarts : 

![image](https://user-images.githubusercontent.com/32641097/37393145-8db9af3c-2770-11e8-977f-a6b2dc44d674.png)

(encart oignon jaune légèrement plus grand que les autres)
