### ISSUE TITLE
la photo du produit est trop grande et déborde sur le texte

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#88]
voir capture d'écran ci dessous : 

![image](https://user-images.githubusercontent.com/32641097/35032402-17b1f32e-fb67-11e7-8b0b-3cfac87fcbff.png)

**Comment by dyslesiq** [comment]
C'est corrigé mais pas encore déployé,  a priori on mettra le site à jour en fin de semaine.
