### ISSUE TITLE
Texte de présentation de la ferme plus grand que les titres des rubriques de présentation

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#89]
D'un point de vue esthétique, je trouve que c'est mieux si le texte est de même taille partout : le texte libre du producteur de même taille que la production, l'année d'installation, etc...
![image](https://user-images.githubusercontent.com/32641097/35032450-3ca4447a-fb67-11e7-882b-f6e024935011.png)

**Comment by dyslesiq** [comment]
C'est corrigé mais pas encore déployé,  a priori on mettra le site à jour en fin de semaine.
