### ISSUE TITLE
texte d'accueil sur la page www.aubenas.stolons.org

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#91]
**Remplacer le texte actuel suivant :** 
"Stolons c’est quoi 
Stolons est une plateforme libre et open source regroupant des structures, appelées Stolon, souhaitant développer une agriculture locale, éthique et écologique tout en créant du lien social et en développant les actions locales. Tous les Stolons vous proposent de composer chaque semaine votre panier de produits locaux, respectueux de l'environnement. De plus les Stolons peuvent vous proposer d'autres services comme un café associatif, des concerts, des bon plans ..."

**par ce texte :** 
« Stolon 
Stolon est une plateforme libre et en open source qui regroupe des structures appelées Stolon qui visent à promouvoir les circuits courts via un site internet et un système de vente hebdomadaire sans engagement. La plateforme Stolon a été créée par une équipe d’informaticiens bénévoles soutenus par l’association des producteurs bio Agri Bio Ardèche.
Les produits proposés au sein des Stolons sont tous certifiés issus de l’Agriculture Biologique, proviennent de moins de 50 kms du lieu de dépôt et sont vendus à un prix de vente directe dans un objectif d’accessibilité au plus grand nombre.
Pour toute question et pour bénéficier d'un compte consommateur, veuillez contacter Jeanne d’Agri Bio Ardèche :  jeanne.ab07@aurabio.org »

**Comment by ChavFDG** [comment]
C'est fait !
