### ISSUE TITLE
Compléter l'image sur page d'accueil www.aubenas.stolons.org

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#92]
ajouter les phrases de description de la BD sur la page d'accueil : 

![image](https://user-images.githubusercontent.com/32641097/35032938-2479ca62-fb69-11e7-9565-72b4b1d60186.png)

**Comment by ChavFDG** [comment]
C'est fait il faudrait juste me donner les textes complémentaire à ajouter en description quand on clique dessus

**Comment by JeanneVoiry** [comment]
le texte : 
"Le principe est simple : chaque semaine, les producteurs mettent en ligne leurs produits et renseignent les stocks disponibles. Pendant la période de commande, les consommateurs composent leur panier en ligne, sans engagement périodique puis les producteurs préparent et livrent les commandes sur un lieu de dépôt le jour convenu."
