### ISSUE TITLE
Ajout logo d'un financeur

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#93]
ajouter ce logo sur la page d'accueil www.aubenas.stolons.org aux autres logo des financeurs 

![rra auvergne](https://user-images.githubusercontent.com/32641097/35033017-68f8562c-fb69-11e7-88a2-9aa3ed5962bf.jpg)

**Comment by ChavFDG** [comment]
C'est fait !

**Comment by JeanneVoiry** [comment]
le logo de la région en s'affiche pas !

**Comment by ChavFDG** [comment]
C'est qu'il faut vider ton cache. Fait ctrl+F5 quand tu es sur la page.
