### ISSUE TITLE
Améliorations sur la pagede présentation du stolon d'aubenas et des stolons (accueil)

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#94]
Sur la page : https://aubenas.stolons.org/Home/StolonContact/ac42c9e5-2118-4402-b60c-b64451ea0df0

plusieurs choses à changer : 
d'une part, faute de frappe : "horaires" et non pas "horarires"
le numéro de tél est à mettre à jour car j'ai changé de bureau : 04 75 64 93 74
les logos des produits : on pourrait mettre un logo par type de produit (fruit/légume/farine/pain/conserve, etc)

**Comment by ChavFDG** [comment]
@JeanneVoiry Le numéro de téléphone se change dans la configuration du stolon.
Pour le reste on travail dessus.

**Comment by ChavFDG** [comment]
A faire :
@JeanneVoiry : écrire les textes à mettre quand on clique sur les 4 images de présentations  
![image](https://user-images.githubusercontent.com/16624098/37291231-85e0f8a0-260e-11e8-91d9-542a2e9ddb8d.png)
@nmichon : Dans le détail d'un stolon faire les TODO 
![image](https://user-images.githubusercontent.com/16624098/37291300-a40db76e-260e-11e8-9601-4d6c9d514607.png)

**Comment by JeanneVoiry** [comment]
Plusieurs remarques sur la page d'accueil https://beta.stolons.org/

D'abord je vois plutôt l'organisation de la page dans l'ordre suivant 

1. logo stolon + "et si on mangeait bio et local" (_inchangé_)

2. Description de Stolon, voici le texte : 
"Stolon, qu'est-ce que c'est ? _(ça ne se dit pas "c'est quoi")_
Stolon est un outil à but non lucratif de commandes hebdomadaires en ligne développé en 2016 par une association citoyenne –Stolon de Privas- et renforcé en 2017 par Agri Bio Ardèche. Le code de l’outil est libre de droit et son développement est participatif : il a mobilisé plusieurs informaticiens bénévoles, consommateurs et producteurs. Les produits proposés au sein des Stolons sont tous certifiés issus de l’Agriculture Biologique, proviennent de moins de 50 km du lieu de dépôt et sont vendus au prix de vente directe pratiqué sur le territoire dans un objectif d’accessibilité au plus grand nombre.

Pour toute question et pour bénéficier d'un compte consommateur, veuillez contacter Agri Bio Ardèche, agribioardeche@aurabio.org, 04 75 64 82 96.

3. Comment ça marche 
Texte pour l'image "je compose mon panier" : Pendant la période de commande, je peux composer et modifier mon panier en ligne à ma guise.

Texte pour l'image "les producteurs récoltent" : A la fin de la période de commande, les producteurs reçoivent les bons de commande et préparent les paniers.

Texte pour l'image "je viens récupérer" : Je viens récupérer mon panier sur le lieu de dépôt le jour convenu et je paie sur place."

4. Trouver un Stolon _(inchangé)_

5. Nos partenaires
