### ISSUE TITLE
les livraisons des producteurs s'affichent en triple dans "gérer les paniers"

### ISSUE THREAD

**Issue by JeanneVoiry** [ChavFDG/Stolons#95]
![image](https://user-images.githubusercontent.com/32641097/35088298-a6e80a98-fc33-11e7-9dcc-2ee0335db8f6.png)

**Comment by ChavFDG** [comment]
Théoriquement le bug est corrigé. Mais à tester
(Il peut rester sur aubenas.stolons.org des factures en double/triples ... on va les supprimer à la main)
